### ISSUE TITLE
pointwise scheduler error

### ISSUE THREAD

**Issue by jjsjann123** [csarofeen/pytorch#1079]
## 🐛 Bug

codegen error from simple script (also seems to be specific to the problem size). Sounds like something with the scheduler.
```
        def f(x: torch.Tensor):
            o = torch.relu(x)
            return torch.dropout(o, 0.5, False)

        jitted = torch.jit.script(f)
        inp = torch.randn(1, 512, 2000, device="cuda").half()
        inp_ref = inp.detach().clone().requires_grad_()
```

```
root@32546b368fbc:/opt/pytorch/pytorch# python test/test_jit_cuda_fuser.py TestCudaFuser.test_pw_scheduler
monkeytype is not installed. Skipping tests for Profile-Directed Typing
E
======================================================================
ERROR: test_pw_scheduler (__main__.TestCudaFuser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 1054, in wrapper
    method(*args, **kwargs)
  File "test/test_jit_cuda_fuser.py", line 2477, in test_pw_scheduler
    jit_o = jitted(inp)
  File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 139, in prof_func_call
    return prof_callable(func_call, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 136, in prof_callable
    return callable(*args, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: Vectorization, unrolling, and unswitching are only supported with start = 0 and extent as a const int, but got a start of 0 and extent i14 .


----------------------------------------------------------------------
Ran 1 test in 11.635s

FAILED (errors=1)
```

## To Reproduce

repro pushed here: https://github.com/csarofeen/pytorch/tree/tacotron2_repro_0

**Comment by jjsjann123** [comment]
No longer repros.
