### ISSUE TITLE
BN + pw fusion hits codegen assert

### ISSUE THREAD

**Issue by jjsjann123** [csarofeen/pytorch#1408]
## 🐛 Bug

Error message I'm getting are
```
======================================================================                                                  
ERROR: test_batch_norm_impl_index_correctness (__main__.TestCudaFuser)                                                     
----------------------------------------------------------------------                                                     
Traceback (most recent call last):                                                                                         
  File "/raid/pytorch_10_1/torch/testing/_internal/common_utils.py", line 1469, in wrapper                                 
    method(*args, **kwargs)                                                                                                
  File "test_jit_cuda_fuser.py", line 2892, in test_batch_norm_impl_index_correctness                                      
    self._test_batch_norm_impl_index_helper(b, c, hw, affine, track_running_stats, training)                               
  File "test_jit_cuda_fuser.py", line 2785, in _test_batch_norm_impl_index_helper                                          
    jit_o.backward(grad)                                                                                                   
  File "/raid/pytorch_10_1/torch/_tensor.py", line 352, in backward                                                        
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)                                     
  File "/raid/pytorch_10_1/torch/autograd/__init__.py", line 173, in backward                                              
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass                         
RuntimeError: The following operation failed in the TorchScript interpreter.                                               
Traceback of TorchScript (most recent call last):                                                                          
RuntimeError: falseINTERNAL ASSERT FAILED at "/raid/pytorch_10_1/torch/csrc/jit/codegen/cuda/executor.cpp":210, please report a bug to PyTorch. Allocations must be based on constant integers for local memory. However, found: T11_l[ iblockIdx.x131{( ceilDiv(T0.size[1], blockDim.x) )}, ithreadIdx.x132{blockDim.x}, iS135{( ceilDiv(( ceilDiv(T0.size[0], blockDim.y) ), 1) )}, ithreadIdx.y134{blockDim.y}, iUS136{1}, sbS28{1}, sbS29{1} ],  have dynamic allocations but are placed in local memory.
```

## To Reproduce

Test pushed here: https://github.com/csarofeen/pytorch/tree/repro_bn_pw
run with `PYTORCH_NVFUSER_DUMP="fusion_ir_math" python test_jit_cuda_fuser.py TestCudaFuser.test_batch_norm_impl_index_correctness`

**Comment by jjsjann123** [comment]
cc'ing @naoyam

**Comment by naoyam** [comment]
Looks like we just need to set computeAt for `T11`:

```
%kernel_math {
T8_l[ iblockIdx.x107{( ceilDiv(i11, blockDim.x) )}, ithreadIdx.x108{blockDim.x}, iS111{( ceilDiv(( ceilDiv(i10, blockDim.y) ), 1) )}, ithreadIdx.y110{blockDim.y}, iUS112{1}, sbS16{1}, sbS17{1} ] ca_pos( 5 )
   = T7_g[ iS113{( ceilDiv(i11, blockDim.x) )}, iS114{blockDim.x}, iS117{( ceilDiv(( ceilDiv(i10, blockDim.y) ), 1) )}, iS116{blockDim.y}, iS118{1}, sbS12{1}, sbS13{1} ]
   * double(2);
T30_l[ iblockIdx.x97{( ceilDiv(i11, blockDim.x) )}, ithreadIdx.x98{blockDim.x}, rS101{( ceilDiv(( ceilDiv(i10, blockDim.y) ), 1) )}rf, ithreadIdx.y100{blockDim.y}rf, rUS102{1}rf, rS95{1}rf, rS96{1}rf ] ca_pos( 2 ) produce_pos( 5) = reduction( T8_l[ iblockIdx.x107{( ceilDiv(i11, blockDim.x) )}, ithreadIdx.x108{blockDim.x}, iS111{( ceilDiv(( ceilDiv(i10, blockDim.y) ), 1) )}, ithreadIdx.y110{blockDim.y}, iUS112{1}, sbS16{1}, sbS17{1} ] ca_pos( 5 ), op = add, initial value = double(0) )
T10_g[ iblockIdx.x104{( ceilDiv(i11, blockDim.x) )}, ithreadIdx.x105{blockDim.x}, rthreadIdx.y106{blockDim.y} ] produce_pos( 2) = reduction( T30_l[ iblockIdx.x97{( ceilDiv(i11, blockDim.x) )}, ithreadIdx.x98{blockDim.x}, rS101{( ceilDiv(( ceilDiv(i10, blockDim.y) ), 1) )}rf, ithreadIdx.y100{blockDim.y}rf, rUS102{1}rf, rS95{1}rf, rS96{1}rf ] ca_pos( 2 ) produce_pos( 5), op = add, initial value = double(0) )
T29_g[ iblockIdx.x119{( ceilDiv(i11, blockDim.x) )}, ithreadIdx.x120{blockDim.x}, iS123{( ceilDiv(( ceilDiv(i10, blockDim.y) ), 1) )}, ithreadIdx.y122{blockDim.y}, iUS124{1}, sbS85{1}, sbS86{1} ] produce_pos( 5)
   = T8_l[ iblockIdx.x107{( ceilDiv(i11, blockDim.x) )}, ithreadIdx.x108{blockDim.x}, iS111{( ceilDiv(( ceilDiv(i10, blockDim.y) ), 1) )}, ithreadIdx.y110{blockDim.y}, iUS112{1}, sbS16{1}, sbS17{1} ] ca_pos( 5 );
T9_l[ iblockIdx.x143{( ceilDiv(i7, blockDim.x) )}, ithreadIdx.x144{blockDim.x}, bS147{( ceilDiv(( ceilDiv(1, blockDim.y) ), 1) )}, bthreadIdx.y146{blockDim.y}, bUS148{1}, bS20{1}, bS21{1} ] = broadcast( T4_g[ iblockIdx.x149{( ceilDiv(i7, blockDim.x) )}, ithreadIdx.x150{blockDim.x} ] )
T11_l[ iblockIdx.x131{( ceilDiv(i2, blockDim.x) )}, ithreadIdx.x132{blockDim.x}, iS135{( ceilDiv(( ceilDiv(i1, blockDim.y) ), 1) )}, ithreadIdx.y134{blockDim.y}, iUS136{1}, sbS28{1}, sbS29{1} ]
   = T0_g[ iS137{( ceilDiv(i2, blockDim.x) )}, iS138{blockDim.x}, iS141{( ceilDiv(( ceilDiv(i1, blockDim.y) ), 1) )}, ithreadIdx.y140{blockDim.y}, iUS142{1}, sbS2{1}, sbS3{1} ]
   - T9_l[ iblockIdx.x143{( ceilDiv(i7, blockDim.x) )}, ithreadIdx.x144{blockDim.x}, bS147{( ceilDiv(( ceilDiv(1, blockDim.y) ), 1) )}, bthreadIdx.y146{blockDim.y}, bUS148{1}, bS20{1}, bS21{1} ];
T12_g[ iblockIdx.x125{( ceilDiv(i11, blockDim.x) )}, ithreadIdx.x126{blockDim.x}, iS129{( ceilDiv(( ceilDiv(i10, blockDim.y) ), 1) )}, ithreadIdx.y128{blockDim.y}, iUS130{1}, sbS32{1}, sbS33{1} ] produce_pos( 5)
   = T8_l[ iblockIdx.x107{( ceilDiv(i11, blockDim.x) )}, ithreadIdx.x108{blockDim.x}, iS111{( ceilDiv(( ceilDiv(i10, blockDim.y) ), 1) )}, ithreadIdx.y110{blockDim.y}, iUS112{1}, sbS16{1}, sbS17{1} ] ca_pos( 5 )
   * T11_l[ iblockIdx.x131{( ceilDiv(i2, blockDim.x) )}, ithreadIdx.x132{blockDim.x}, iS135{( ceilDiv(( ceilDiv(i1, blockDim.y) ), 1) )}, ithreadIdx.y134{blockDim.y}, iUS136{1}, sbS28{1}, sbS29{1} ];
T23_g[ iblockIdx.x151{( ceilDiv(i2, blockDim.x) )}, ithreadIdx.x152{blockDim.x}, iS155{( ceilDiv(( ceilDiv(i1, blockDim.y) ), 1) )}, ithreadIdx.y154{blockDim.y}, iUS156{1}, sbS64{1}, sbS65{1} ]
   = T0_g[ iS137{( ceilDiv(i2, blockDim.x) )}, iS138{blockDim.x}, iS141{( ceilDiv(( ceilDiv(i1, blockDim.y) ), 1) )}, ithreadIdx.y140{blockDim.y}, iUS142{1}, sbS2{1}, sbS3{1} ]
   - T9_l[ iblockIdx.x143{( ceilDiv(i7, blockDim.x) )}, ithreadIdx.x144{blockDim.x}, bS147{( ceilDiv(( ceilDiv(1, blockDim.y) ), 1) )}, bthreadIdx.y146{blockDim.y}, bUS148{1}, bS20{1}, bS21{1} ];
}
```

Pinging @csarofeen
