### ISSUE TITLE
Indexing failure with view

### ISSUE THREAD

**Issue by naoyam** [csarofeen/pytorch#1493]
This test fails at indexing with the TOT branch:

```
TEST_F(NVFuserTest, FusionViewConcreteDomain2_CUDA) {
  Fusion fusion;
  FusionGuard fg(&fusion);

  auto tv0 = makeSymbolicTensor(2);
  fusion.addInput(tv0);
  auto tv1 = makeContigTensor(2);
  fusion.addInput(tv1);

  auto tv2 = view(tv0, {2, 3}, {6});
  auto tv3 = add(tv2, IrBuilder::create<Double>(1));
  auto tv4 = broadcast(tv3, {true, false});
  auto tv5 = add(tv4, tv1);

  fusion.addOutput(tv5);

  tv5->merge(0);
  tv0->computeAt(tv5, -1);
  tv1->computeAt(tv5, -1);

  fusion.printMath();
  fusion.printKernel();
}
```

```
C++ exception with description "root_ind != nullptrINTERNAL ASSERT FAILED at "../torch/csrc/jit/codegen/cuda/index_compute.cpp":1492, please report a bug to PyTorch. Couldn't find root mapping for TV1 dim: 1 id: iS21{T1.size[0]}
```

The problem seems to have something to do with how we choose concrete domains.

The failure fusion was based on the failing case of https://github.com/csarofeen/pytorch/pull/1451/files/f582e16adf5d1681d76a181cd3a17c217df6da45?show-viewed-files=true&file-filters%5B%5D=#r813879270, but simplified to reproduce with TOT.

**Comment by naoyam** [comment]
Here's the CA Loop map:

```
Loop map
  disjoint_set{ iS19{T0.size[0]}*, iS17{T0.size[0]} }
  disjoint_set{ iS20{T0.size[1]}*, iS18{T0.size[1]} }
  disjoint_set{ iS14{( T0.size[0] * T0.size[1] )}*, iS6{( T0.size[0] * T0.size[1] )}rf, iS7{( T0.size[0] * T0.size[1] )}, iS13{( 1 * ( T0.size[0] * T0.size[1] ) )}, iS9{( T0.size[0] * T0.size[1] )}, iS12{( T1.size[0] * ( T0.size[0] * T0.size[1] ) )}, iS11{( T0.size[0] * T0.size[1] )}, iS15{( T1.size[0] * T1.size[1] )}, iS22{T1.size[1]} }
  disjoint_set{ bS8{1}, iS16{T1.size[0]}*, iS21{T1.size[0]} }
```

The problem is this set: `disjoint_set{ iS14{( T0.size[0] * T0.size[1] )}*, iS6{( T0.size[0] * T0.size[1] )}rf, iS7{( T0.size[0] * T0.size[1] )}, iS13{( 1 * ( T0.size[0] * T0.size[1] ) )}, iS9{( T0.size[0] * T0.size[1] )}, iS12{( T1.size[0] * ( T0.size[0] * T0.size[1] ) )}, iS11{( T0.size[0] * T0.size[1] )}, iS15{( T1.size[0] * T1.size[1] )}, iS22{T1.size[1]} }`. Notice that `iS14{( T0.size[0] * T0.size[1] )}` is selected as the concrete domain, although the set contains other domains with more concrete domains, `iS12{( T1.size[0] * ( T0.size[0] * T0.size[1] ) )}`. When counting the number of root concrete domains of `iS12`, `T0.size[0] * T0.size[1]` is counted as just one as it is derived from a view merged rfactor domain, so the the counter of `iS12` is just two, not exceeding `iS14`.

**Comment by rdspring1** [comment]
Another failing case after the fix:
```
TEST_F(NVFuserTest, FusionViewConcreteDomain2_CUDA) {
  constexpr int kAxis = -1;
  std::vector<int64_t> input_shape = {19, 12, 7, 99};
  std::vector<int64_t> output_shape = {19, 3, 2772};

  std::unique_ptr<Fusion> fusion_ptr = std::make_unique<Fusion>();
  Fusion& fusion = *fusion_ptr.get();
  FusionGuard fg(&fusion);

  TensorView* x = makeSymbolicTensor(input_shape.size());
  TensorView* bias = makeSymbolicTensor(output_shape.size());
  fusion.addInput(x);
  fusion.addInput(bias);

  auto tv1 = softmax(x, kAxis);
  auto x_view = view(tv1, input_shape, output_shape);
  auto y = add(x_view, bias);
  fusion.addOutput(y);

  auto options = at::TensorOptions().dtype(at::kFloat).device(at::kCUDA, 0);
  at::Tensor at_x = at::randn(input_shape, options);
  at::Tensor at_bias = at::randn(output_shape, options);
  std::vector<IValue> aten_inputs = {at_x, at_bias};

  FusionExecutorCache fusion_executor_cache(std::move(fusion_ptr));
  auto outputs = fusion_executor_cache.runFusionWithInputs(aten_inputs);

  auto at_tv1 = at::_softmax(at_x, kAxis, false /* half_to_float */);
  auto at_x_view = at::native::view(at_tv1, output_shape);
  auto at_y = at::add(at_x_view, at_bias);

  testValidate(&fusion, outputs, aten_inputs, {at_y}, __LINE__, __FILE__);
}
```

```
C++ exception with description "root_vals.find(inp) != root_vals.end() INTERNAL ASSERT FAILED at "../torch/csrc/jit/codegen/cuda/ir_nodes.cpp":1093, please report a bug to PyTorch. Invalid tensor domain, iS234{T5.size[2]} is an input of domain, but it is not found in the root domain.
```

**Comment by kevinstephano** [comment]
I am seeing this error in multihead attention with AOT Autograd:

```
Traceback (most recent call last):
  File "xformer_feed_fwd.py", line 83, in <module>
    runner.run(sys.argv, TestModule(1024, 4096, 0.1), optim_func, input_func, grad_func) 
  File "/workspace/simple_dl_models/engines/runner.py", line 81, in run
    test_times.append((name, engine.train_loop(args, model, optim_func, input_func, grad_func) / args.steps * 1000.0))
  File "/workspace/simple_dl_models/engines/aot_autograd_engine.py", line 30, in train_loop
    loss = aot_model(*batch)
  File "/opt/pytorch/pytorch/torch/nn/modules/module.py", line 1111, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/functorch/functorch/_src/aot_autograd.py", line 491, in forward
    return compiled_f(
  File "/workspace/functorch/functorch/_src/aot_autograd.py", line 451, in returned_function
    out = cached_fn(*flat_tensor_args)
  File "/workspace/functorch/functorch/_src/aot_autograd.py", line 161, in forward
    fw_outs = normalize_as_list(compiled_fw(*flat_tensor_args))
  File "/opt/pytorch/pytorch/torch/nn/modules/module.py", line 1111, in _call_impl
    return forward_call(*input, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: rhs_i >= 0 && lhs_i >= 0 INTERNAL ASSERT FAILED at "../torch/csrc/jit/codegen/cuda/scheduler/pointwise.cpp":648, please report a bug to PyTorch.
```
You can recreate by doing the following:

1.) Setup AOT Autograd

```
git clone https://github.com/pytorch/functorch.git
cd functorch; pip install -e .[aot]
```

2.) Run test

```
git clone https://github.com/kevinstephano/simple_dl_models.git
cd simple_dl_models
python xformer_multihead_attn.py --skip_eager --aot_autograd
```

**Comment by naoyam** [comment]
I think I now know what's going on. I'll try some ideas.

**Comment by naoyam** [comment]
In Ryan's repro, the second segmented fusion is:

```
inputs:
T1_g[ iS4{i5}, iS5{i6}, iS6{i7} ] float
T5_g[ iS19{i1}, iS20{i2}, iS21{i3}, iS22{i4} ] float
T8_g[ iS31{i1}, iS32{i2}, iS33{i3}, bS34{1} ] float
outputs:
T11_g[ iS47{i1}, iS48{3}, iS49{( ( ( ceilDiv(i2, 3) ) * i3 ) * i4 )} ] float


T9_l[ iS35{i1}, iS36{i2}, iS37{i3}, iS38{i4} ]
   = T5_g[ iS19{i1}, iS20{i2}, iS21{i3}, iS22{i4} ]
   * T8_g[ iS31{i1}, iS32{i2}, iS33{i3}, bS34{1} ];
T10_g[ iS39{i1}, iS43{3}rf, iS46{( ( ( ceilDiv(i2, 3) ) * i3 ) * i4 )}rf ] = view( T9_l[ iS35{i1}, iS36{i2}, iS37{i3}, iS38{i4} ] )
T11_g[ iS47{i1}, iS48{3}, iS49{( ( ( ceilDiv(i2, 3) ) * i3 ) * i4 )} ]
   = T10_g[ iS39{i1}, iS43{3}rf, iS46{( ( ( ceilDiv(i2, 3) ) * i3 ) * i4 )}rf ]
   + T1_g[ iS4{i5}, iS5{i6}, iS6{i7} ];
```

This is scheduled as:

```
Inputs:
  T1_g[ iS106{( ceilDiv(( ceilDiv(( i6 * i7 ), blockDim.x) ), 4) )}, iblockIdx.x108{( ceilDiv(i5, 1) )}, iUS109{1}, iS107{4}, iS105{blockDim.x} ], float
  T5_g[ iS139{( ceilDiv(( ceilDiv(( 3 * ( ( ( ceilDiv(i2, 3) ) * i3 ) * i4 ) ), blockDim.x) ), 4) )}, iS141{( ceilDiv(i1, 1) )}, iS142{1}, iS140{4}, iS138{blockDim.x} ], float
  T8_g[ iS150{( ceilDiv(( ceilDiv(( 3 * ( ( ( ceilDiv(i2, 3) ) * i3 ) * 1 ) ), blockDim.x) ), 4) )}, iS152{( ceilDiv(i1, 1) )}, iS153{1}, iS151{4}, iS149{blockDim.x} ], float
Outputs:
  T11_g[ iblockIdx.y67{( ceilDiv(( ceilDiv(( 3 * ( ( ( ceilDiv(i2, 3) ) * i3 ) * i4 ) ), blockDim.x) ), 4) )}, iblockIdx.x69{( ceilDiv(i1, 1) )}, iUS70{1}, iS68{4}, ithreadIdx.x66{blockDim.x} ] produce_pos( 3), float

%kernel_math {
T13_l[ iblockIdx.y117{( ceilDiv(( ceilDiv(( 3 * ( ( ( ceilDiv(i2, 3) ) * i3 ) * i4 ) ), blockDim.x) ), 4) )}, iblockIdx.x119{( ceilDiv(i1, 1) )}, iUS120{1}, iS118{4}, ithreadIdx.x116{blockDim.x} ] ca_pos( 3 )
   = T5_g[ iS139{( ceilDiv(( ceilDiv(( 3 * ( ( ( ceilDiv(i2, 3) ) * i3 ) * i4 ) ), blockDim.x) ), 4) )}, iS141{( ceilDiv(i1, 1) )}, iS142{1}, iS140{4}, iS138{blockDim.x} ];
T14_l[ iblockIdx.y128{( ceilDiv(( ceilDiv(( 3 * ( ( ( ceilDiv(i2, 3) ) * i3 ) * 1 ) ), blockDim.x) ), 4) )}, iblockIdx.x130{( ceilDiv(i1, 1) )}, iUS131{1}, iS129{4}, ithreadIdx.x127{blockDim.x} ] ca_pos( 3 )
   = T8_g[ iS150{( ceilDiv(( ceilDiv(( 3 * ( ( ( ceilDiv(i2, 3) ) * i3 ) * 1 ) ), blockDim.x) ), 4) )}, iS152{( ceilDiv(i1, 1) )}, iS153{1}, iS151{4}, iS149{blockDim.x} ];
T9_l[ iblockIdx.y99{( ceilDiv(( ceilDiv(( 3 * ( ( ( ceilDiv(i2, 3) ) * i3 ) * i4 ) ), blockDim.x) ), 4) )}, iblockIdx.x101{( ceilDiv(i1, 1) )}, iUS102{1}, iS100{4}, ithreadIdx.x98{blockDim.x} ] ca_pos( 5 ) produce_pos( 3)
   = T13_l[ iblockIdx.y117{( ceilDiv(( ceilDiv(( 3 * ( ( ( ceilDiv(i2, 3) ) * i3 ) * i4 ) ), blockDim.x) ), 4) )}, iblockIdx.x119{( ceilDiv(i1, 1) )}, iUS120{1}, iS118{4}, ithreadIdx.x116{blockDim.x} ] ca_pos( 3 )
   * T14_l[ iblockIdx.y128{( ceilDiv(( ceilDiv(( 3 * ( ( ( ceilDiv(i2, 3) ) * i3 ) * 1 ) ), blockDim.x) ), 4) )}, iblockIdx.x130{( ceilDiv(i1, 1) )}, iUS131{1}, iS129{4}, ithreadIdx.x127{blockDim.x} ] ca_pos( 3 );
T10_l[ iblockIdx.y81{( ceilDiv(( ceilDiv(( 3 * ( ( ( ceilDiv(i2, 3) ) * i3 ) * i4 ) ), blockDim.x) ), 4) )}rf, iblockIdx.x83{( ceilDiv(i1, 1) )}, iUS84{1}, iS82{4}rf, ithreadIdx.x80{blockDim.x}rf ] ca_pos( 5 ) produce_pos( 5) = view( T9_l[ iblockIdx.y99{( ceilDiv(( ceilDiv(( 3 * ( ( ( ceilDiv(i2, 3) ) * i3 ) * i4 ) ), blockDim.x) ), 4) )}, iblockIdx.x101{( ceilDiv(i1, 1) )}, iUS102{1}, iS100{4}, ithreadIdx.x98{blockDim.x} ] ca_pos( 5 ) produce_pos( 3) )
T12_l[ iblockIdx.y88{( ceilDiv(( ceilDiv(( i6 * i7 ), blockDim.x) ), 4) )}, iblockIdx.x90{( ceilDiv(i5, 1) )}, iUS91{1}, iS89{4}, ithreadIdx.x87{blockDim.x} ] ca_pos( 3 )
   = T1_g[ iS106{( ceilDiv(( ceilDiv(( i6 * i7 ), blockDim.x) ), 4) )}, iblockIdx.x108{( ceilDiv(i5, 1) )}, iUS109{1}, iS107{4}, iS105{blockDim.x} ];
T15_l[ iblockIdx.y74{( ceilDiv(( ceilDiv(( 3 * ( ( ( ceilDiv(i2, 3) ) * i3 ) * i4 ) ), blockDim.x) ), 4) )}, iblockIdx.x76{( ceilDiv(i1, 1) )}, iUS77{1}, iS75{4}, ithreadIdx.x73{blockDim.x} ] ca_pos( 3 ) produce_pos( 5)
   = T10_l[ iblockIdx.y81{( ceilDiv(( ceilDiv(( 3 * ( ( ( ceilDiv(i2, 3) ) * i3 ) * i4 ) ), blockDim.x) ), 4) )}rf, iblockIdx.x83{( ceilDiv(i1, 1) )}, iUS84{1}, iS82{4}rf, ithreadIdx.x80{blockDim.x}rf ] ca_pos( 5 ) produce_pos( 5)
   + T12_l[ iblockIdx.y88{( ceilDiv(( ceilDiv(( i6 * i7 ), blockDim.x) ), 4) )}, iblockIdx.x90{( ceilDiv(i5, 1) )}, iUS91{1}, iS89{4}, ithreadIdx.x87{blockDim.x} ] ca_pos( 3 );
T11_g[ iblockIdx.y67{( ceilDiv(( ceilDiv(( 3 * ( ( ( ceilDiv(i2, 3) ) * i3 ) * i4 ) ), blockDim.x) ), 4) )}, iblockIdx.x69{( ceilDiv(i1, 1) )}, iUS70{1}, iS68{4}, ithreadIdx.x66{blockDim.x} ] produce_pos( 3)
   = T15_l[ iblockIdx.y74{( ceilDiv(( ceilDiv(( 3 * ( ( ( ceilDiv(i2, 3) ) * i3 ) * i4 ) ), blockDim.x) ), 4) )}, iblockIdx.x76{( ceilDiv(i1, 1) )}, iUS77{1}, iS75{4}, ithreadIdx.x73{blockDim.x} ] ca_pos( 3 ) produce_pos( 5);
}
```

The error happens when creating a reference tensor for indexing `T14` as a non-global consumer tensor. The reason we have a problem with the tensor is that the domains of left of its CA position have concrete domains picked from the post-view tensors, whereas the concrete domains of the other domains of `T14` are from the pre-view tensors, and in this case it results in inconsistent reference replay. When traversing up from the pre-view concrete domains, they can reach up to the initial root domains, however, when traversing from the post-view concrete domains, they can only reach up to the view rfactor domains. Specifically, these are the domains created as the root domains of the reference tensors:

```
Root: iS221{T1.size[0]}
Root: iS230{T5.size[1]}
Root: iS220{( ( ( ceilDiv(T5.size[1], 3) ) * T5.size[2] ) * T5.size[3] )}
```

The first two are created by traversing the pre-view domains, but the last one gets stuck at the rfactor domain. This inconsistency results in the error detected at creating a TensorDomain. (I'm glad to have the error check in TensorDomain).

I think the reference tensor should have the complete history of transformations no matter how views are involved. I'm thinking about creating a chain of concrete domains per each CA map group so that we could traverse back through view rfactor operations.

**Comment by naoyam** [comment]
> I am seeing this error in multihead attention with AOT Autograd:
> 
> ```
> Traceback (most recent call last):
>   File "xformer_feed_fwd.py", line 83, in <module>
>     runner.run(sys.argv, TestModule(1024, 4096, 0.1), optim_func, input_func, grad_func) 
>   File "/workspace/simple_dl_models/engines/runner.py", line 81, in run
>     test_times.append((name, engine.train_loop(args, model, optim_func, input_func, grad_func) / args.steps * 1000.0))
>   File "/workspace/simple_dl_models/engines/aot_autograd_engine.py", line 30, in train_loop
>     loss = aot_model(*batch)
>   File "/opt/pytorch/pytorch/torch/nn/modules/module.py", line 1111, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/workspace/functorch/functorch/_src/aot_autograd.py", line 491, in forward
>     return compiled_f(
>   File "/workspace/functorch/functorch/_src/aot_autograd.py", line 451, in returned_function
>     out = cached_fn(*flat_tensor_args)
>   File "/workspace/functorch/functorch/_src/aot_autograd.py", line 161, in forward
>     fw_outs = normalize_as_list(compiled_fw(*flat_tensor_args))
>   File "/opt/pytorch/pytorch/torch/nn/modules/module.py", line 1111, in _call_impl
>     return forward_call(*input, **kwargs)
> RuntimeError: The following operation failed in the TorchScript interpreter.
> Traceback of TorchScript (most recent call last):
> RuntimeError: rhs_i >= 0 && lhs_i >= 0 INTERNAL ASSERT FAILED at "../torch/csrc/jit/codegen/cuda/scheduler/pointwise.cpp":648, please report a bug to PyTorch.
> ```
> 
> You can recreate by doing the following:
> 
> 1.) Setup AOT Autograd
> 
> ```
> git clone https://github.com/pytorch/functorch.git
> cd functorch; pip install -e .[aot]
> ```
> 
> 2.) Run test
> 
> ```
> git clone https://github.com/kevinstephano/simple_dl_models.git
> cd simple_dl_models
> python xformer_multihead_attn.py --skip_eager --aot_autograd
> ```

@kevinstephano Can you please try #1509? I'm still running the Python tests, but Ryan's repro is fixed.

**Comment by kevinstephano** [comment]
I am getting a new error with your fix, Naoya.

```
Traceback (most recent call last):
  File "xformer_multihead_attn.py", line 108, in <module>
    runner.run(sys.argv, TestModule(1024, 16, 0.1), optim_func, input_func, grad_func) 
  File "/workspace/simple_dl_models/engines/runner.py", line 81, in run
    test_times.append((name, engine.train_loop(args, model, optim_func, input_func, grad_func) / args.steps * 1000.0))
  File "/workspace/simple_dl_models/engines/aot_autograd_engine.py", line 30, in train_loop
    loss = aot_model(*batch)
  File "/opt/pytorch/pytorch/torch/nn/modules/module.py", line 1111, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/functorch/functorch/_src/aot_autograd.py", line 491, in forward
    return compiled_f(
  File "/workspace/functorch/functorch/_src/aot_autograd.py", line 451, in returned_function
    out = cached_fn(*flat_tensor_args)
  File "/workspace/functorch/functorch/_src/aot_autograd.py", line 161, in forward
    fw_outs = normalize_as_list(compiled_fw(*flat_tensor_args))
  File "/opt/pytorch/pytorch/torch/nn/modules/module.py", line 1111, in _call_impl
    return forward_call(*input, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: it != replay_CasP.getReplay().end() INTERNAL ASSERT FAILED at "../torch/csrc/jit/codegen/cuda/transform_replay.cpp":487, please report a bug to PyTorch. Could not find axis, iS184{( ceilDiv(( ceilDiv(( ceilDiv(( 64 * ( ( ceilDiv(i4, 64) ) * ( i5 * i6 ) ) ), 4) ), 1) ), 128) )}, requested in replay.
```

**Comment by kevinstephano** [comment]
I tried to repro the failure from above by going through the backward fusion groups and creating them in TorchScript.  I could only get one to fail.  The same failure occurs when I run the test with AOT Autograd and doesn't exactly reproduce the failure seen above.

Here is the test case:

```
import torch

class Fusion(torch.nn.Module) :
    def __init__(self) :
        super(Fusion, self).__init__()

    def forward(self, inputs) :
        out1 = inputs.view(128, 64, 1024)
        out2 = out1.sum((0,1), keepdim=True)
        out3 = out2.view(1024)
        return (out3, out1)


if __name__ == "__main__" :
   inputs = torch.randn(1024, 64, 128, device='cuda')
   p_inputs = inputs.permute(2,0,1)

   model = Fusion().cuda()
   model = torch.jit.script(model)

   with torch.jit.fuser('fuser2') :
       with torch.inference_mode() :
           for _ in range(5) :
               out = model(p_inputs)
 ```
 
 Error:
 ```
 
CUDA NVRTC compile error: default_program(3341): error: identifier "i0" is undefined

default_program(3341): error: identifier "i2" is undefined

2 errors detected in the compilation of "default_program".
```

**Comment by rdspring1** [comment]
Apply distinct view transformations to two different pre-view tensors.
These tensors map to a common shape and are used together in a binary operation.
```
TEST_F(NVFuserTest, FusionViewConcreteDomain3_CUDA) {
  std::vector<int64_t> input_shape = {14, 12, 8, 100};
  std::vector<int64_t> bcast_shape = {14, 12, 8, 1};
  std::vector<int64_t> other_shape = {14, 100, 96};
  std::vector<int64_t> output_shape = {14, 3, 3200};

  std::unique_ptr<Fusion> fusion_ptr = std::make_unique<Fusion>();
  Fusion& fusion = *fusion_ptr.get();
  FusionGuard fg(&fusion);

  TensorView* x = makeSymbolicTensor(input_shape.size());
  TensorView* y = makeConcreteTensor(bcast_shape);
  TensorView* z = makeSymbolicTensor(other_shape.size());
  fusion.addInput(x);
  fusion.addInput(y);
  fusion.addInput(z);

  auto tv1 = add(x, y);
  auto tv2 = view(tv1, input_shape, output_shape);
  auto tv3 = view(z, other_shape, output_shape);
  auto output = add(tv2, tv3);
  fusion.addOutput(output);

  auto options = at::TensorOptions().dtype(at::kFloat).device(at::kCUDA, 0);
  at::Tensor at_x = at::randn(input_shape, options);
  at::Tensor at_y = at::randn(bcast_shape, options);
  at::Tensor at_z = at::randn(other_shape, options);
  std::vector<IValue> aten_inputs = {at_x, at_y, at_z};

  FusionExecutorCache fusion_executor_cache(std::move(fusion_ptr));
  auto outputs = fusion_executor_cache.runFusionWithInputs(aten_inputs);

  auto at_tv1 = at::add(at_x, at_y);
  auto at_tv2 = at::native::view(at_tv1, output_shape);
  auto at_tv3 = at::native::view(at_z, output_shape);
  auto at_output = at::add(at_tv2, at_tv3);

  testValidate(&fusion, outputs, aten_inputs, {at_output}, __LINE__, __FILE__);
}
```

**Comment by naoyam** [comment]
@rdspring1 @kevinstephano  Can we close this? I think with #1536 these fusions should now work, although it may not be complete.

**Comment by naoyam** [comment]
Closing this as I believe it's working now. Please reopen if not.
