### ISSUE TITLE
`devel` branch has failing python tests

### ISSUE THREAD

**Issue by zasdfgbnm** [csarofeen/pytorch#1621]
### 🐛 Describe the bug

```
FAILED test/test_jit_cuda_fuser.py::TestCudaFuserOpInfoCUDA::test_nvfuser_correctness_reshape_cuda_bool - RuntimeError: The following operation failed in the TorchScript interpreter.
FAILED test/test_jit_cuda_fuser.py::TestCudaFuserOpInfoCUDA::test_nvfuser_correctness_reshape_cuda_float32 - RuntimeError: The following operation failed in the TorchScript interpreter.
FAILED test/test_jit_cuda_fuser.py::TestCudaFuserOpInfoCUDA::test_nvfuser_correctness_reshape_cuda_float64 - RuntimeError: The following operation failed in the TorchScript interpreter.
FAILED test/test_jit_cuda_fuser.py::TestCudaFuserOpInfoCUDA::test_nvfuser_correctness_reshape_cuda_int32 - RuntimeError: The following operation failed in the TorchScript interpreter.
FAILED test/test_jit_cuda_fuser.py::TestCudaFuserOpInfoCUDA::test_nvfuser_correctness_reshape_cuda_int64 - RuntimeError: The following operation failed in the TorchScript interpreter.
FAILED test/test_jit_cuda_fuser.py::TestCudaFuserOpInfoCUDA::test_nvfuser_correctness_sum_to_size_cuda_bool - RuntimeError: The following operation failed in the TorchScript interpreter.
FAILED test/test_jit_cuda_fuser.py::TestCudaFuserOpInfoCUDA::test_nvfuser_correctness_sum_to_size_cuda_float32 - RuntimeError: The following operation failed in the TorchScript interpreter.
FAILED test/test_jit_cuda_fuser.py::TestCudaFuserOpInfoCUDA::test_nvfuser_correctness_sum_to_size_cuda_float64 - RuntimeError: The following operation failed in the TorchScript interpreter.
FAILED test/test_jit_cuda_fuser.py::TestCudaFuserOpInfoCUDA::test_nvfuser_correctness_sum_to_size_cuda_int32 - RuntimeError: The following operation failed in the TorchScript interpreter.
FAILED test/test_jit_cuda_fuser.py::TestCudaFuserOpInfoCUDA::test_nvfuser_correctness_sum_to_size_cuda_int64 - RuntimeError: The following operation failed in the TorchScript interpreter.
FAILED test/test_jit_cuda_fuser.py::TestCudaFuserOpInfoCUDA::test_nvfuser_correctness_view_cuda_bool - RuntimeError: The following operation failed in the TorchScript interpreter.
FAILED test/test_jit_cuda_fuser.py::TestCudaFuserOpInfoCUDA::test_nvfuser_correctness_view_cuda_float32 - RuntimeError: The following operation failed in the TorchScript interpreter.
FAILED test/test_jit_cuda_fuser.py::TestCudaFuserOpInfoCUDA::test_nvfuser_correctness_view_cuda_float64 - RuntimeError: The following operation failed in the TorchScript interpreter.
FAILED test/test_jit_cuda_fuser.py::TestCudaFuserOpInfoCUDA::test_nvfuser_correctness_view_cuda_int32 - RuntimeError: The following operation failed in the TorchScript interpreter.
FAILED test/test_jit_cuda_fuser.py::TestCudaFuserOpInfoCUDA::test_nvfuser_correctness_view_cuda_int64 - RuntimeError: The following operation failed in the TorchScript interpreter.
FAILED test/test_jit_cuda_fuser.py::TestCudaFuser::test_unary_ops - AssertionError: False is not true
```

Example error message:
```python
_____________________________________________________________________________________________ TestCudaFuserOpInfoCUDA.test_nvfuser_correctness_view_cuda_int64 ______________________________________________________________________________________________
Traceback (most recent call last):
  File "/home/gaoxiang/.local/lib/python3.10/site-packages/torch/jit/_fuser.py", line 81, in _script_method_graph_for
    dbs = parent.get_debug_state()
RuntimeError: optimized_plan_ INTERNAL ASSERT FAILED at "/home/gaoxiang/pytorch-nvfuser/torch/csrc/jit/runtime/profiling_graph_executor_impl.cpp":708, please report a bug to PyTorch. 
Exception raised from getDebugState at /home/gaoxiang/pytorch-nvfuser/torch/csrc/jit/runtime/profiling_graph_executor_impl.cpp:708 (most recent call first):
frame #0: <unknown function> + 0x5c01d (0x7f2e513e401d in /home/gaoxiang/.local/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x5bd83 (0x7f2e513e3d83 in /home/gaoxiang/.local/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #2: <unknown function> + 0x5bb47 (0x7f2e513e3b47 in /home/gaoxiang/.local/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #3: <unknown function> + 0x5cbd6 (0x7f2e513e4bd6 in /home/gaoxiang/.local/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #4: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x40 (0x7f2e513e29f2 in /home/gaoxiang/.local/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #5: c10::detail::torchCheckFail(char const*, char const*, unsigned int, char const*) + 0x97 (0x7f2e513e0836 in /home/gaoxiang/.local/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #6: <unknown function> + 0x2bcf71 (0x7f2d6e72bf71 in /home/gaoxiang/.local/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
frame #7: torch::jit::ProfilingGraphExecutorImpl::getDebugState() + 0x8a (0x7f2d617e53b2 in /home/gaoxiang/.local/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #8: torch::jit::GraphExecutor::getDebugState() + 0x41 (0x7f2d6178e831 in /home/gaoxiang/.local/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #9: <unknown function> + 0xaec4d5 (0x7f2d6ef5b4d5 in /home/gaoxiang/.local/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
frame #10: <unknown function> + 0xb230e9 (0x7f2d6ef920e9 in /home/gaoxiang/.local/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
frame #11: <unknown function> + 0xb1d08b (0x7f2d6ef8c08b in /home/gaoxiang/.local/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
frame #12: <unknown function> + 0xb0f77d (0x7f2d6ef7e77d in /home/gaoxiang/.local/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
frame #13: <unknown function> + 0xb0f823 (0x7f2d6ef7e823 in /home/gaoxiang/.local/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
frame #14: <unknown function> + 0x2c8a0a (0x7f2d6e737a0a in /home/gaoxiang/.local/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gaoxiang/pytorch-nvfuser/test/test_jit_cuda_fuser.py", line 4644, in test_nvfuser_correctness
    trace(*clone_inputs((sample.input, *sample.args)), **sample.kwargs)
  File "/home/gaoxiang/.local/lib/python3.10/site-packages/torch/testing/_internal/jit_metaprogramming_utils.py", line 371, in traced_fn
    traced_fn.last_graph = traced.graph_for(*inputs_tensors)  # type: ignore[attr-defined]
  File "/home/gaoxiang/.local/lib/python3.10/site-packages/torch/jit/_fuser.py", line 77, in _graph_for
    return _script_method_graph_for(self, self, *args, **kwargs)
  File "/home/gaoxiang/.local/lib/python3.10/site-packages/torch/jit/_fuser.py", line 106, in _script_method_graph_for
    self(*args, **kwargs)
  File "/home/gaoxiang/.local/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 428, in prof_func_call
    return prof_callable(func_call, *args, **kwargs)
  File "/home/gaoxiang/.local/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 425, in prof_callable
    return callable(*args, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: entry_it != disjointSetMap().end() INTERNAL ASSERT FAILED at "/home/gaoxiang/pytorch-nvfuser/torch/csrc/jit/codegen/cuda/disjoint_set.h":185, please report a bug to PyTorch. Strict mapping failed on element: T0_g[ iS0{i0} ] either an error occured, or non strict mapping should have been used.

_______________________________________________________________________________________________________________ TestCudaFuser.test_unary_ops ________________________________________________________________________________________________________________
Traceback (most recent call last):
  File "/home/gaoxiang/pytorch-nvfuser/test/test_jit_cuda_fuser.py", line 617, in test_unary_ops
    self._unary_test_helper(op, dtype, False)  # test special numbers
  File "/home/gaoxiang/pytorch-nvfuser/test/test_jit_cuda_fuser.py", line 567, in _unary_test_helper
    self.assertTrue(self._compare("failing case {}\n{}\n{}\n{}".format(dtype, operation, x, y), o, jit_o, 1e-2))
  File "/usr/lib/python3.10/unittest/case.py", line 687, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
------------------------------------------------------------------------------------------------------------------- Captured stdout call --------------------------------------------------------------------------------------------------------------------
failing case torch.bfloat16
<built-in method exp of type object at 0x7f2d6fd9bfe0>
tensor([    -inf, -10.0000,  -3.1406,  -1.0000,  -0.5000,   0.0000,   1.0000,
          0.5000,   3.1406,  10.0000,      inf,      nan], device='cuda:0',
       dtype=torch.bfloat16)
tensor([0.4004, 0.2559, 0.0859, 0.1943, 0.6953, 0.6250, 0.8477, 0.2070, 0.7227,
        0.8320, 0.3809, 0.9922], device='cuda:0', dtype=torch.bfloat16) False
dif    :  tensor([[ -0.1250],
        [-48.0000]], device='cuda:0', dtype=torch.bfloat16)
inp1   :  tensor([[   9.6250],
        [4080.0000]], device='cuda:0', dtype=torch.bfloat16)
inp2   :  tensor([[   9.7500],
        [4128.0000]], device='cuda:0', dtype=torch.bfloat16)
maximum difference tensor(-0.1250, device='cuda:0', dtype=torch.bfloat16)
```

### Versions

devel

**Comment by jjsjann123** [comment]
Ha, that's better than I expected... but the sum failure makes me nervous.... :)

**Comment by jjsjann123** [comment]
I think these have been patched in our last upstream push. Though I'm not totally sure if view/reshape are handled properly in codegen, since we disabled those, but that's a different topic.

I'm going to close it for now.
