### ISSUE TITLE
Empty graph is not supported

### ISSUE THREAD

**Issue by zasdfgbnm** [csarofeen/pytorch#1808]
### 🐛 Describe the bug

```c++
TEST_F(NVFuserTest, FusionEmptyGraph_CUDA) {
  auto fusion = std::make_unique<Fusion>();
  FusionGuard fg(fusion.get());

  TensorView* tv0 = makeContigTensor(2);

  fusion->addInput(tv0);
  fusion->addOutput(tv0);

  auto options = at::TensorOptions().dtype(at::kFloat).device(at::kCUDA, 0);
  auto aten_input = at::randn({5, 10}, options);

  FusionExecutorCache fec(std::move(fusion));
  std::vector<IValue> aten_inputs = {aten_input};
  auto outputs = fec.runFusionWithInputs(aten_inputs);

  TORCH_CHECK(at::allclose(aten_input, outputs[0]));
}
```
```
unknown file: Failure
C++ exception with description "entry_it != disjointSetMap().end() INTERNAL ASSERT FAILED at "/home/gaoxiang/nvfuser/torch/csrc/jit/codegen/cuda/disjoint_set.h":218, please report a bug to PyTorch. Strict mapping failed on element: T0_g[ iS0{i1}, iS1{i2} ] either an error occured, or non strict mapping should have been used.
Exception raised from strictAreMapped at /home/gaoxiang/nvfuser/torch/csrc/jit/codegen/cuda/disjoint_set.h:218 (most recent call first):
frame #0: <unknown function> + 0x85b50 (0x7fae03766b50 in /home/gaoxiang/nvfuser/build/lib/libc10.so)
frame #1: <unknown function> + 0x85ae0 (0x7fae03766ae0 in /home/gaoxiang/nvfuser/build/lib/libc10.so)
frame #2: <unknown function> + 0x859e0 (0x7fae037669e0 in /home/gaoxiang/nvfuser/build/lib/libc10.so)
frame #3: <unknown function> + 0x87c48 (0x7fae03768c48 in /home/gaoxiang/nvfuser/build/lib/libc10.so)
frame #4: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x65 (0x7fae03767265 in /home/gaoxiang/nvfuser/build/lib/libc10.so)
frame #5: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x7a (0x7fae03764c0a in /home/gaoxiang/nvfuser/build/lib/libc10.so)
frame #6: c10::detail::torchInternalAssertFail(char const*, char const*, unsigned int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x5d (0x7fae03764e7d in /home/gaoxiang/nvfuser/build/lib/libc10.so)
frame #7: <unknown function> + 0x6944160 (0x7fae1abb1160 in /home/gaoxiang/nvfuser/build/lib/libtorch_cuda.so)
frame #8: <unknown function> + 0x6936046 (0x7fae1aba3046 in /home/gaoxiang/nvfuser/build/lib/libtorch_cuda.so)
frame #9: <unknown function> + 0x6935ac8 (0x7fae1aba2ac8 in /home/gaoxiang/nvfuser/build/lib/libtorch_cuda.so)
frame #10: torch::jit::fuser::cuda::SchedulerEntry::canSchedule(torch::jit::fuser::cuda::ScheduleHeuristic, torch::jit::fuser::cuda::Fusion*, torch::jit::fuser::cuda::SchedulerRuntimeInfo&, torch::jit::fuser::cuda::HeuristicSummary*) + 0x79 (0x7fae1aba29b9 in /home/gaoxiang/nvfuser/build/lib/libtorch_cuda.so)
frame #11: torch::jit::fuser::cuda::SchedulerEntry::proposeHeuristics(torch::jit::fuser::cuda::Fusion*, torch::jit::fuser::cuda::SchedulerRuntimeInfo&) + 0x7c (0x7fae1abaad0c in /home/gaoxiang/nvfuser/build/lib/libtorch_cuda.so)
frame #12: torch::jit::fuser::cuda::FusionKernelRuntime::FusionKernelRuntime(torch::jit::fuser::cuda::Fusion*, c10::ArrayRef<c10::IValue> const&) + 0x1a3 (0x7fae1a9b79d3 in /home/gaoxiang/nvfuser/build/lib/libtorch_cuda.so)
frame #13: <unknown function> + 0x6756381 (0x7fae1a9c3381 in /home/gaoxiang/nvfuser/build/lib/libtorch_cuda.so)
frame #14: torch::jit::fuser::cuda::FusionExecutorCache::getKernelRuntimeFor(c10::ArrayRef<c10::IValue> const&, unsigned long) + 0x246 (0x7fae1a9b5826 in /home/gaoxiang/nvfuser/build/lib/libtorch_cuda.so)
frame #15: torch::jit::fuser::cuda::FusionExecutorCache::runFusionWithInputs(c10::ArrayRef<c10::IValue> const&) + 0x54f (0x7fae1a9b516f in /home/gaoxiang/nvfuser/build/lib/libtorch_cuda.so)
frame #16: torch::jit::NVFuserTest_FusionInputIsOutput_CUDA_Test::TestBody() + 0x31e (0x55e0d8fc581e in ./build/bin/test_jit)
frame #17: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) + 0x7b (0x55e0d91e6f9b in ./build/bin/test_jit)
frame #18: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) + 0x7d (0x55e0d91cf93d in ./build/bin/test_jit)
frame #19: testing::Test::Run() + 0xc3 (0x55e0d91a7de3 in ./build/bin/test_jit)
frame #20: testing::TestInfo::Run() + 0x106 (0x55e0d91a8c76 in ./build/bin/test_jit)
frame #21: testing::TestSuite::Run() + 0x111 (0x55e0d91a9521 in ./build/bin/test_jit)
frame #22: testing::internal::UnitTestImpl::RunAllTests() + 0x45b (0x55e0d91bb6eb in ./build/bin/test_jit)
frame #23: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) + 0x7b (0x55e0d91e9a0b in ./build/bin/test_jit)
frame #24: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) + 0x83 (0x55e0d91d20e3 in ./build/bin/test_jit)
frame #25: testing::UnitTest::Run() + 0xd5 (0x55e0d91bb225 in ./build/bin/test_jit)
frame #26: <unknown function> + 0x376cd1 (0x55e0d89fecd1 in ./build/bin/test_jit)
frame #27: main + 0x226 (0x55e0d89fec76 in ./build/bin/test_jit)
frame #28: <unknown function> + 0x29290 (0x7fae032c7290 in /usr/lib/libc.so.6)
frame #29: __libc_start_main + 0x8a (0x7fae032c734a in /usr/lib/libc.so.6)
frame #30: _start + 0x25 (0x55e0d89fe8a5 in ./build/bin/test_jit)
" thrown in the test body.
```
This is blocking my upstream PR https://github.com/pytorch/pytorch/pull/79824. I am wondering whether I should add support for this case to nvFuser, or should modify the primTorch executor to avoid this case.

### Versions

```
Collecting environment information...
PyTorch version: 1.13.0a0+gitd8d8a48
Is debug build: True
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Arch Linux (x86_64)
GCC version: (GCC) 12.1.0
Clang version: 14.0.6
CMake version: version 3.23.2
Libc version: glibc-2.35

Python version: 3.10.5 (main, Jun  6 2022, 18:49:26) [GCC 12.1.0] (64-bit runtime)
Python platform: Linux-5.18.9-arch1-1-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.7.64
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 2080 Ti

Nvidia driver version: 515.57
cuDNN version: Probably one of the following:
/usr/lib/libcudnn.so.8.4.1
/usr/lib/libcudnn_adv_infer.so.8.4.1
/usr/lib/libcudnn_adv_train.so.8.4.1
/usr/lib/libcudnn_cnn_infer.so.8.4.1
/usr/lib/libcudnn_cnn_train.so.8.4.1
/usr/lib/libcudnn_ops_infer.so.8.4.1
/usr/lib/libcudnn_ops_train.so.8.4.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] torch==1.13.0a0+gitfcf389a
[pip3] torch-ucc==1.0.0
[pip3] torchani==2.2
[pip3] torchvision==0.2.2.post3
[conda] Could not collect
```

**Comment by zasdfgbnm** [comment]
cc @kevinstephano @jjsjann123

**Comment by zasdfgbnm** [comment]
Also @IvanYashchuk, the refs for `real` is:
```python
def real(a: TensorLikeType) -> TensorLikeType:
    assert isinstance(a, TensorLike)
    if utils.is_complex_dtype(a.dtype):
        return prims.real(a)
    return a
```
For non-complex cases, it returns the input tensor itself, and this creates an empty nvFuser graph. Not sure if it is possible to just not create any fusion for that path.

**Comment by jjsjann123** [comment]
forwarding input tensors is not supported yet and we probably should extend it there. would need some work to support it. In TS, it's currently handled in integration code and TorchScript graph somewhat naturally. I imagine this would take quite some work to handle in codegen. cc'ing @shmsong @csarofeen 

cc'ing @kevinstephano, feels like this is something we can think about supporting in your new caching / python API.

Meanwhile for the scope of your PR. We can add a quick WAR to copy all output that's forwarded from input in fusion API. This is not safe in general, since we are breaking the aliasing, but I think prim is supposed to be functional(?!?!) so we might be good. :crossed_fingers:

**Comment by jjsjann123** [comment]
errr... python test does check on alias....

```
root@0cbb91360e92:/opt/pytorch/pytorch/test# python test_ops.py -k test_python_ref_executor__refs_real_executor_nvfuser_cuda_float32 -v -f
test_python_ref_executor__refs_real_executor_nvfuser_cuda_float32 (__main__.TestCommonCUDA) ... FAIL

======================================================================
FAIL: test_python_ref_executor__refs_real_executor_nvfuser_cuda_float32 (__main__.TestCommonCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 1806, in wrapper
    method(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 1806, in wrapper
    method(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_device_type.py", line 377, in instantiated_test
    result = test(self, **param_kwargs)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_device_type.py", line 813, in test_wrapper
    return test(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_device_type.py", line 970, in only_fn
    return fn(slf, *args, **kwargs)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_device_type.py", line 848, in dep_fn
    return fn(slf, *args, **kwargs)
  File "test_ops.py", line 540, in test_python_ref_executor
    self._ref_test_helper(
  File "test_ops.py", line 407, in _ref_test_helper
    self.assertEqual(a._is_view(), b._is_view())
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 2249, in assertEqual
    assert_equal(
  File "/opt/pytorch/pytorch/torch/testing/_comparison.py", line 1093, in assert_equal
    raise error_metas[0].to_error(msg)
AssertionError: Booleans mismatch: False is not True

----------------------------------------------------------------------
Ran 1 test in 10.098s

FAILED (failures=1)

```

Let's keep the discussion here for aliasing support. Meanwhile, for the upstream PR, let's just disable nvfuser test for now.... :cry: cc'ing @zasdfgbnm

**Comment by zasdfgbnm** [comment]
@jjsjann123 Thanks for checking!

**Comment by zasdfgbnm** [comment]
It is pretty hard to get aliasing correct. For example, `torch.real(x)` is a view for complex input as well, but I don't have an idea on how to make nvFuser return a view for that case... Same for `torch.view_as_real`. And also, consider a more complicated case: `torch.real(x).transpose(0, 1)[1,:].view(-1, 2)`, how do we make sure we return an alias? ¯\_(ツ)_/¯

**Comment by shmsong** [comment]
referencing related issue in #1385. 

In the case of forwarding input we could potentially just skip code gen and kernel launch and same tensorview should just show up on the output.

**Comment by shmsong** [comment]
> It is pretty hard to get aliasing correct. For example, `torch.real(x)` is a view for complex input as well, but I don't have an idea on how to make nvFuser return a view for that case... Same for `torch.view_as_real`. And also, consider a more complicated case: `torch.real(x).transpose(0, 1)[1,:].view(-1, 2)`, how do we make sure we return an alias? ¯_(ツ)_/¯

Sorry didn't see this part when sending the last reply. I thought it was forwarding inputs as described in this issue, but returning an alias is definitely tricky to handle once they're on the Fusion graph already.

**Comment by jjsjann123** [comment]
> > It is pretty hard to get aliasing correct. For example, `torch.real(x)` is a view for complex input as well, but I don't have an idea on how to make nvFuser return a view for that case... Same for `torch.view_as_real`. And also, consider a more complicated case: `torch.real(x).transpose(0, 1)[1,:].view(-1, 2)`, how do we make sure we return an alias? ¯_(ツ)_/¯
> 
> Sorry didn't see this part when sending the last reply. I thought it was forwarding inputs as described in this issue, but returning an alias is definitely tricky to handle once they're on the Fusion graph already.

@zasdfgbnm 
Currently with nvfuser there's no good way to do that except some 'leaked' code from TS integration. https://github.com/csarofeen/pytorch/blob/282c42902bff07f759cddbbe619249cf5e7c5281/torch/csrc/jit/codegen/cuda/fusion.h#L179-L189

But we don't have a way to handle things like transpose/view yet, except some limited permutation support in TS integration that's not in codegen. We might be able to do something in python integration for prim though, given that Kevin has a side light-weight representation, where we have a chance to replay those. But again, there's going to be extra work to support that.

Back to our actual permutation/view support in TS, we use TS alias analysis on the graph and only fuses alias ops where aliases can be safely dropped. e.g. `y = x.view(-1, 2).relu()`. the alias from `view` is consumed by `relu` and returns a copy, so we can safely drop the alias in fusion: https://github.com/csarofeen/pytorch/blob/282c42902bff07f759cddbbe619249cf5e7c5281/torch/csrc/jit/codegen/cuda/graph_fuser.cpp#L2178

**Comment by IvanYashchuk** [comment]
> errr... python test does check on alias....

It can be skipped with `validate_view_consistency=False` in the `torch/testing/_internal/common_methods_invocations.py` file for the specific OpInfo.
For example view consistency is disabled for reduction ops: https://github.com/pytorch/pytorch/issues/77216.
