### ISSUE TITLE
Segfault at lowering

### ISSUE THREAD

**Issue by zasdfgbnm** [csarofeen/pytorch#1851]
### 🐛 Describe the bug

```C++
TEST_F(NVFuserTest, SimpleSmemCopy) {
  Fusion fusion;
  FusionGuard fg(&fusion);

  auto tv0 = makeContigTensor(1);
  fusion.addInput(tv0);
  auto tv1 = set(tv0);
  auto tv2 = set(tv1);
  fusion.addOutput(tv2);

  tv1->setMemoryType(MemoryType::Shared);

  tv0->split(0, 4);
  tv0->split(0, 128);
  tv0->axis(-1)->parallelize(ParallelType::Vectorize);

  MaxRootDomainInfoSpanningTree spanning_tree(tv0);
  TransformPropagator propagator(tv0, 2);
  spanning_tree.traverse(&propagator);
  scheduler_utils::parallelizeAllLike(tv0);
  InlinePropagator inline_propagator(tv0, 2);
  spanning_tree.traverse(&inline_propagator);

  fusion.print();
  fusion.printMath();
  fusion.printKernel();
}
```
gdb
```gdb
Thread 1 "test_jit" received signal SIGSEGV, Segmentation fault.
std::vector<torch::jit::fuser::cuda::Val*, std::allocator<torch::jit::fuser::cuda::Val*> >::size (this=0x20) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.1.0/../../../../include/c++/12.1.0/bits/stl_vector.h:988
988           { return size_type(this->_M_impl._M_finish - this->_M_impl._M_start); }
(gdb) bt
#0  std::vector<torch::jit::fuser::cuda::Val*, std::allocator<torch::jit::fuser::cuda::Val*> >::size (this=0x20) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.1.0/../../../../include/c++/12.1.0/bits/stl_vector.h:988
#1  0x00007fffd7780a25 in std::vector<torch::jit::fuser::cuda::Val*, std::allocator<torch::jit::fuser::cuda::Val*> >::_M_range_check (this=0x20, __n=0)
    at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.1.0/../../../../include/c++/12.1.0/bits/stl_vector.h:1152
#2  0x00007fffd77809e1 in std::vector<torch::jit::fuser::cuda::Val*, std::allocator<torch::jit::fuser::cuda::Val*> >::at (this=0x20, __n=0) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.1.0/../../../../include/c++/12.1.0/bits/stl_vector.h:1194
#3  0x00007fffd7a90319 in torch::jit::fuser::cuda::(anonymous namespace)::VectorizeValidator::validate (tv=0x555558afdd70) at /home/gaoxiang/nvfuser2/torch/csrc/jit/codegen/cuda/lower_validation.cpp:453
#4  0x00007fffd7a8f461 in torch::jit::fuser::cuda::validateAndCollectVectorizeInfo (fusion=0x555558a8a710) at /home/gaoxiang/nvfuser2/torch/csrc/jit/codegen/cuda/lower_validation.cpp:557
#5  0x00007fffd7aa8e42 in torch::jit::fuser::cuda::GpuLower::lower (this=0x7fffffffc000, fusion=0x7fffffffcbc0, index_type=torch::jit::fuser::cuda::DataType::Int) at /home/gaoxiang/nvfuser2/torch/csrc/jit/codegen/cuda/lower2device.cpp:274
#6  0x00007fffd77b5604 in torch::jit::fuser::cuda::GpuLower::GpuLower (this=0x7fffffffc000, fusion=0x7fffffffcbc0, index_type=torch::jit::fuser::cuda::DataType::Int) at /home/gaoxiang/nvfuser2/torch/csrc/jit/codegen/cuda/lower2device.h:53
#7  0x00007fffd7863e35 in torch::jit::fuser::cuda::Fusion::printKernel (this=0x7fffffffcbc0, index_type=torch::jit::fuser::cuda::DataType::Int) at /home/gaoxiang/nvfuser2/torch/csrc/jit/codegen/cuda/fusion.cpp:348
#8  0x0000555555ea1f90 in torch::jit::NVFuserTest_SimpleSmemCopy_Test::TestBody (this=0x555558a963e0) at /home/gaoxiang/nvfuser2/torch/csrc/jit/codegen/cuda/test/test_gpu.cpp:24773
#9  0x00005555560c94cb in testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void> (object=0x555558a963e0, method=&virtual testing::Test::TestBody(), location=0x55555617372f "the test body")
    at /home/gaoxiang/nvfuser2/third_party/googletest/googletest/src/gtest.cc:2607
#10 0x00005555560b1e6d in testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void> (object=0x555558a963e0, method=&virtual testing::Test::TestBody(), location=0x55555617372f "the test body")
    at /home/gaoxiang/nvfuser2/third_party/googletest/googletest/src/gtest.cc:2643
#11 0x000055555608a313 in testing::Test::Run (this=0x555558a963e0) at /home/gaoxiang/nvfuser2/third_party/googletest/googletest/src/gtest.cc:2682
#12 0x000055555608b1a6 in testing::TestInfo::Run (this=0x555558a62350) at /home/gaoxiang/nvfuser2/third_party/googletest/googletest/src/gtest.cc:2861
#13 0x000055555608ba51 in testing::TestSuite::Run (this=0x555558a2c430) at /home/gaoxiang/nvfuser2/third_party/googletest/googletest/src/gtest.cc:3015
#14 0x000055555609dc1b in testing::internal::UnitTestImpl::RunAllTests (this=0x5555589cbfc0) at /home/gaoxiang/nvfuser2/third_party/googletest/googletest/src/gtest.cc:5855
#15 0x00005555560cbf3b in testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (object=0x5555589cbfc0, 
    method=(bool (testing::internal::UnitTestImpl::*)(testing::internal::UnitTestImpl * const)) 0x55555609d7c0 <testing::internal::UnitTestImpl::RunAllTests()>, location=0x555556173fbc "auxiliary test code (environments or event listeners)")
    at /home/gaoxiang/nvfuser2/third_party/googletest/googletest/src/gtest.cc:2607
#16 0x00005555560b4613 in testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (object=0x5555589cbfc0, 
    method=(bool (testing::internal::UnitTestImpl::*)(testing::internal::UnitTestImpl * const)) 0x55555609d7c0 <testing::internal::UnitTestImpl::RunAllTests()>, location=0x555556173fbc "auxiliary test code (environments or event listeners)")
    at /home/gaoxiang/nvfuser2/third_party/googletest/googletest/src/gtest.cc:2643
#17 0x000055555609d755 in testing::UnitTest::Run (this=0x5555563dd450 <testing::UnitTest::GetInstance()::instance>) at /home/gaoxiang/nvfuser2/third_party/googletest/googletest/src/gtest.cc:5438
#18 0x00005555558d1fc1 in RUN_ALL_TESTS () at /home/gaoxiang/nvfuser2/cmake/../third_party/googletest/googletest/include/gtest/gtest.h:2490
#19 0x00005555558d1f66 in main (argc=1, argv=0x7fffffffd5d8) at /home/gaoxiang/nvfuser2/test/cpp/common/main.cpp:31
```

### Versions

devel

**Comment by naoyam** [comment]
I suspect that's because you're vectorizing a fusion input tensor, and the validation implicitly assumes vectorized tensors are indeed generated in a fusion. Vectorizing inputs doesn't make any sense, so we could make it error out, but more generally we don't disallow parallelizing input tensors, so it seems to make sense to let vectorization be just a silent operation. An easy fix would be to skip input tensors in the vectorization validation.
