### ISSUE TITLE
Codegen Failure found in Bias+Gelu Backward Kernel with FP16 Dtype

### ISSUE THREAD

**Issue by kevinstephano** [csarofeen/pytorch#1877]
### 🐛 Describe the bug

The bias+gelu backward kernel which is really gelu_backward + an outer reduction for the bias is failing with the FP16 Data Type.  This fusion is found in the backward pass of Transformer networks.

Error:
```
Traceback (most recent call last):
  File "repro.py", line 65, in <module>
    out.backward(grad)
  File "/opt/pytorch/pytorch/torch/_tensor.py", line 484, in backward
    torch.autograd.backward(
  File "/opt/pytorch/pytorch/torch/autograd/__init__.py", line 191, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: !fallback_mode_enabled_ INTERNAL ASSERT FAILED at "/opt/pytorch/pytorch/torch/csrc/jit/codegen/cuda/lower_expr_sort.cpp":921, please report a bug to PyTorch. Couldn't succcessfully sort out the fusion expressions. There are remaining connections of the heirarchical segmentation which should have been flattened to a single ordered group, or disjoint ordered groups.
```

Here is a repro script:

```
import torch

class TestModule(torch.nn.Module):
    def __init__(self, hidden_size, intermediate_size):
        super(TestModule, self).__init__()
        self.lin1 = torch.nn.Linear(hidden_size, intermediate_size, bias=True)

    def forward(self, hidden_states):
        out1 = self.lin1(hidden_states)
        out2 = torch.nn.functional.gelu(out1, approximate='tanh')
        return out2

model = TestModule(1024, 4096)
model.half()
model.cuda()
jit_model = torch.jit.script(model)

data = torch.randn(128, 64, 1024, dtype=torch.float16, device='cuda', requires_grad=True)
grad = torch.randn(128, 64, 4096, dtype=torch.float16, device='cuda')

for _ in range(5) :
    out = jit_model(data)
    out.backward(grad)
    data.grad = None

```

Execution Command:
```
PYTORCH_NVFUSER_DISABLE=fallback python repro.py
```

This is the Fusion Group from TorchScript:

```
[DUMP graph_fuser.cpp:2506] with prim::CudaFusionGroup_0 = graph(%4 : Half(128, 64, 4096, strides=[262144, 4096, 1], requires_grad=0, device=cuda:0),
[DUMP graph_fuser.cpp:2506]       %5 : Half(128, 64, 4096, strides=[262144, 4096, 1], requires_grad=0, device=cuda:0)):
[DUMP graph_fuser.cpp:2506]   %1 : int[] = prim::Constant[value=[4096]]() 
[DUMP graph_fuser.cpp:2506]   %6 : str = prim::Constant[value="tanh"]()
[DUMP graph_fuser.cpp:2506]   %7 : Half(128, 64, 4096, strides=[262144, 4096, 1], requires_grad=0, device=cuda:0) = aten::gelu_backward(%4, %5, %6) # <string>:112:23
[DUMP graph_fuser.cpp:2506]   %grad_bias.5 : Half(4096, strides=[1], requires_grad=0, device=cuda:0) = aten::_grad_sum_to_size(%7, %1) # <string>:70:31
[DUMP graph_fuser.cpp:2506]   return (%grad_bias.5, %7)
```

### Versions

TOT

**Comment by kevinstephano** [comment]
This was actually fixed when I tried in the csarofeen fork.  The fix just wasn't propagated to upstream, yet.
