### ISSUE TITLE
AMP batch_norm doesn't work well

### ISSUE THREAD

**Issue by xwang233** [csarofeen/pytorch#1894]
### 🐛 Describe the bug

Reproduce:

TIMM repo

```python
python -u benchmark.py --bench train --model ens_adv_inception_resnet_v2 --img-size 224 -b 128 --amp --torchscript --fuser nvfuser
```

Error:
```python
root@c73318efaa9b:/workspace/timm-models/pytorch-image-models# python -u benchmark.py --bench train --model ens_adv_inception_resnet_v2 --img-size 224 -b 128 --amp --torchscript --fuser nvfuser 
WARNING: Overriding precision to 'amp' since --amp flag set.
Benchmarking in amp precision. NCHW layout. torchscript enabled
Model ens_adv_inception_resnet_v2 created, param count: 55843464
Running train benchmark on ens_adv_inception_resnet_v2 for 40 steps w/ input size (3, 224, 224) and batch size 128.
ERROR: "The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "<string>", line 19, in <backward op>

            def backward(grad_output):
                dinput, dweight, dbias = torch._batch_norm_impl_index_backward(
                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
                    impl_idx, input, grad_output, weight, running_mean, running_var,
                    save1, save2, training, eps, [True, has_weight, has_bias], reserve)
RuntimeError: Expected tensor for argument #1 'input' to have the same type as tensor for argument #2 'grad_output'; but type torch.cuda.HalfTensor does not equal torch.cuda.FloatTensor (while checking arguments for cudnn_batch_norm_backward)
" while running benchmark.
Traceback (most recent call last):
  File "benchmark.py", line 721, in <module>
    main()
  File "benchmark.py", line 705, in main
    results = benchmark(args)
  File "benchmark.py", line 637, in benchmark
    run_results = _try_run(
  File "benchmark.py", line 584, in _try_run
    results = bench.run()
  File "benchmark.py", line 443, in run
    _step()
  File "benchmark.py", line 422, in _step
    self.loss(output, target).backward()
  File "/opt/pytorch/pytorch/functorch/functorch/_src/monkey_patching.py", line 77, in _backward
    return _old_backward(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_tensor.py", line 484, in backward
    torch.autograd.backward(
  File "/opt/pytorch/pytorch/torch/autograd/__init__.py", line 191, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "<string>", line 19, in <backward op>

            def backward(grad_output):
                dinput, dweight, dbias = torch._batch_norm_impl_index_backward(
                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
                    impl_idx, input, grad_output, weight, running_mean, running_var,
                    save1, save2, training, eps, [True, has_weight, has_bias], reserve)
RuntimeError: Expected tensor for argument #1 'input' to have the same type as tensor for argument #2 'grad_output'; but type torch.cuda.HalfTensor does not equal torch.cuda.FloatTensor (while checking arguments for cudnn_batch_norm_backward)
```

### Versions

nightly core build 5589033

**Comment by csarofeen** [comment]
This looks like torch script AMP, I assume this doesn't repro with the dynamo/aot stack?
We won't make improvements to torch script based amp, so will likely close this as will not fix.
CC @jjsjann123

**Comment by xwang233** [comment]
That's right. We haven't seen similar batch_norm + half/float error messages in dynamo/aot benchmarks yet. It's only in torchscript benchmark.
