### ISSUE TITLE
Python test failure with transpose

### ISSUE THREAD

**Issue by naoyam** [csarofeen/pytorch#1968]
Failed with TOT. Is this a known problem?

```
======================================================================
ERROR: test_batch_norm_impl_index_inner_bcast (__main__.TestCudaFuser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nmaruyama/pytorch/debug1/torch/testing/_internal/common_utils.py", line 1940, in wrapper
    method(*args, **kwargs)
  File "test/test_jit_cuda_fuser.py", line 3359, in test_batch_norm_impl_index_inner_bcast
    self._test_batch_norm_impl_index_helper(2, 1, 1, affine, track_running_stats, training)
  File "test/test_jit_cuda_fuser.py", line 3260, in _test_batch_norm_impl_index_helper
    jit_o.backward(grad)
  File "/home/nmaruyama/pytorch/debug1/torch/_tensor.py", line 484, in backward
    torch.autograd.backward(
  File "/home/nmaruyama/pytorch/debug1/torch/autograd/__init__.py", line 191, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: mapped_id != nullptr INTERNAL ASSERT FAILED at "../torch/csrc/jit/codegen/cuda/scheduler/transpose.cpp":75, please report a bug to PyTorch. Can not find ID mapped to bS61{1} in tensor T1_g[ bS4{1} ]
```

**Comment by naoyam** [comment]
Tagging @zasdfgbnm

**Comment by zasdfgbnm** [comment]
This is a new problem introduced with the enablement of the transpose scheduler, fixed in https://github.com/csarofeen/pytorch/pull/1969
