### ISSUE TITLE
Missing cast op in batch_norm composite op for TorchBench pytorch_stargan

### ISSUE THREAD

**Issue by rdspring1** [csarofeen/pytorch#2087]
### 🐛 Describe the bug

`PYTORCH_NVFUSER_DUMP=python_definition,fusion_args python benchmarks/torchbench.py --training -d cuda --fast --backend nvprims_nvfuser --skip-accuracy-check --performance --only pytorch_stargan
`
```python
def nvfuser_fusion_id0(fd : FusionDefinition) -> None :
    T0 = fd.define_tensor(symbolic_sizes=[-1, -1, -1, -1], contiguous=[True, True, True, True], dtype=DataType.Float)
    T1 = fd.define_tensor(symbolic_sizes=[-1], contiguous=[True], dtype=DataType.Float)
    T2 = fd.define_tensor(symbolic_sizes=[-1], contiguous=[True], dtype=DataType.Float)
    T3 = fd.define_tensor(symbolic_sizes=[-1], contiguous=[True], dtype=DataType.Float)
    T4 = fd.define_tensor(symbolic_sizes=[-1], contiguous=[True], dtype=DataType.Float)
    T5 = fd.ops.view(T0, original_shape=[16, 64, 128, 128], new_shape=[1, 1024, 128, 128])
    T6 = fd.ops.broadcast_in_dim(T1, output_shape=[16, 64], broadcast_dims=[1])
    T7 = fd.ops.broadcast_in_dim(T2, output_shape=[16, 64], broadcast_dims=[1])
    T8 = fd.ops.broadcast_in_dim(T3, output_shape=[16, 64], broadcast_dims=[1])
    T9 = fd.ops.broadcast_in_dim(T4, output_shape=[16, 64], broadcast_dims=[1])
    T10 = fd.ops.set(T6)
    T11 = fd.ops.set(T7)
    T12 = fd.ops.set(T8)
    T13 = fd.ops.set(T9)
    T14 = fd.permute(T10)
    T15 = fd.permute(T11)
    T16 = fd.permute(T12)
    T17 = fd.permute(T13)
    T18 = fd.ops.view(T14, original_shape=[16, 64], new_shape=[1024])
    T19 = fd.ops.view(T15, original_shape=[16, 64], new_shape=[1024])
    T20 = fd.ops.view(T16, original_shape=[16, 64], new_shape=[1024])
    T21 = fd.ops.view(T17, original_shape=[16, 64], new_shape=[1024])
    S22 = fd.define_constant(0.100000)
    S23 = fd.define_constant(1.00000e-05)
    T24, T25, T26 = fd.ops.batch_norm(T5, T18, T19, T20, T21, S22, S23)
    fd.add_output(T5)
    fd.add_output(T18)
    fd.add_output(T20)
    fd.add_output(T21)
    fd.add_output(T24)
    fd.add_output(T25)
    fd.add_output(T26)
```

`RuntimeError: unary_op->isA<UnaryOp>() && unary_op->as<UnaryOp>()->getUnaryOpType() == UnaryOpType::Cast INTERNAL ASSERT FAILED at "../torch/csrc/jit/codegen/cuda/ops/normalization.cpp":540, please report a bug to PyTorch. check for cast op`

```
Traceback (most recent call last):
  File "/home/rds4/workspace/nvprims-torchdynamo/benchmarks/common.py", line 1174, in warmup
    fn(model, example_inputs)
  File "/home/rds4/anaconda3/lib/python3.8/site-packages/torchdynamo-1.13.0.dev0-py3.8-linux-x86_64.egg/torchdynamo/eval_frame.py", line 175, in _fn
    return fn(*args, **kwargs)
  File "benchmarks/torchbench.py", line 358, in forward_and_backward_pass
  File "benchmarks/torchbench.py", line 359, in <graph break in forward_and_backward_pass>
  File "benchmarks/torchbench.py", line 362, in <graph break in forward_and_backward_pass>
  File "/home/rds4/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/rds4/workspace/torchbench/torchbenchmark/models/pytorch_stargan/model.py", line 55, in forward
    def forward(self, x, c):
  File "/home/rds4/anaconda3/lib/python3.8/site-packages/torchdynamo-1.13.0.dev0-py3.8-linux-x86_64.egg/torchdynamo/eval_frame.py", line 175, in _fn
    return fn(*args, **kwargs)
  File "/home/rds4/anaconda3/lib/python3.8/site-packages/functorch/_src/aot_autograd.py", line 837, in forward
    return compiled_f(
  File "/home/rds4/anaconda3/lib/python3.8/site-packages/functorch/_src/aot_autograd.py", line 828, in new_func
    return compiled_fn(args)
  File "/home/rds4/anaconda3/lib/python3.8/site-packages/functorch/_src/aot_autograd.py", line 230, in g
    return f(*args)
  File "/home/rds4/anaconda3/lib/python3.8/site-packages/functorch/_src/aot_autograd.py", line 474, in compiled_function
    return CompiledFunction.apply(*remove_dupe_args(args))
  File "/home/rds4/anaconda3/lib/python3.8/site-packages/torchdynamo-1.13.0.dev0-py3.8-linux-x86_64.egg/torchdynamo/eval_frame.py", line 175, in _fn
    return fn(*args, **kwargs)
  File "/home/rds4/anaconda3/lib/python3.8/site-packages/functorch/_src/aot_autograd.py", line 441, in forward
    fw_outs = call_func_with_args(
  File "/home/rds4/anaconda3/lib/python3.8/site-packages/functorch/_src/aot_autograd.py", line 264, in call_func_with_args
    out = normalize_as_list(f(*args))
  File "/home/rds4/anaconda3/lib/python3.8/site-packages/torch/_prims/executor.py", line 25, in execute
    return nvfuser_execute_partitioned(
  File "/home/rds4/anaconda3/lib/python3.8/site-packages/torch/_prims/nvfuser_executor.py", line 414, in nvfuser_execute_partitioned
    return gm(*args)
  File "/home/rds4/anaconda3/lib/python3.8/site-packages/torch/fx/graph_module.py", line 660, in call_wrapped
    return self._wrapped_call(self, *args, **kwargs)
  File "/home/rds4/anaconda3/lib/python3.8/site-packages/torch/fx/graph_module.py", line 279, in __call__
    raise e
  File "/home/rds4/anaconda3/lib/python3.8/site-packages/torch/fx/graph_module.py", line 269, in __call__
    return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
  File "/home/rds4/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "<eval_with_key>.637", line 12, in forward
    fused_27 = self.fused_27(convolution, arg1_1, arg2_1, arg52_1, arg53_1);  convolution = arg1_1 = arg2_1 = arg52_1 = arg53_1 = None
  File "/home/rds4/anaconda3/lib/python3.8/site-packages/torch/_prims/nvfuser_executor.py", line 266, in __call__
    return nvfuser_execute(
  File "/home/rds4/anaconda3/lib/python3.8/site-packages/torch/_prims/nvfuser_executor.py", line 205, in nvfuser_execute
    fusion, unflatten_spec = make_nvfuser_fusion(gm, *nv_template_args)  # type: ignore[misc]
  File "/home/rds4/anaconda3/lib/python3.8/site-packages/torch/_prims/nvfuser_executor.py", line 178, in make_nvfuser_fusion
    fd.add_output(o)
```

### Versions

torchbenchPerf b117161 + cherry-pick [eedc290](https://github.com/csarofeen/pytorch/commit/eedc290302b90d61ef0ce0a5bfd344463d43c92b)

**Comment by rdspring1** [comment]
Graph Module:
```
def forward(self, broadcast_in_dim_2, broadcast_in_dim_3, broadcast_in_dim_4, broadcast_in_dim_1, view_6):
    clone_2 = torch.ops.nvprims.clone.default(broadcast_in_dim_2, memory_format = torch.preserve_format);  broadcast_in_dim_2 = None
    clone_3 = torch.ops.nvprims.clone.default(broadcast_in_dim_3, memory_format = torch.preserve_format);  broadcast_in_dim_3 = None
    clone_4 = torch.ops.nvprims.clone.default(broadcast_in_dim_4, memory_format = torch.preserve_format);  broadcast_in_dim_4 = None
    clone_1 = torch.ops.nvprims.clone.default(broadcast_in_dim_1, memory_format = torch.preserve_format);  broadcast_in_dim_1 = None
    transpose_2 = torch.ops.nvprims.transpose.default(clone_2, [0, 1]);  clone_2 = None
    transpose_3 = torch.ops.nvprims.transpose.default(clone_3, [0, 1]);  clone_3 = None
    transpose_4 = torch.ops.nvprims.transpose.default(clone_4, [0, 1]);  clone_4 = None
    transpose_1 = torch.ops.nvprims.transpose.default(clone_1, [0, 1]);  clone_1 = None
    view_3 = torch.ops.nvprims.view.default(transpose_2, [16, 64], [1024]);  transpose_2 = None
    view_4 = torch.ops.nvprims.view.default(transpose_3, [16, 64], [1024]);  transpose_3 = None
    view_5 = torch.ops.nvprims.view.default(transpose_4, [16, 64], [1024]);  transpose_4 = None
    view_2 = torch.ops.nvprims.view.default(transpose_1, [16, 64], [1024]);  transpose_1 = None
    native_batch_norm = torch.ops.nvprims.native_batch_norm.default(view_6, view_2, view_3, view_4, view_5, True, 0.1, 1e-05);  view_6 = view_3 = None
    getitem = native_batch_norm[0]
    getitem_1 = native_batch_norm[1]
    getitem_2 = native_batch_norm[2];  native_batch_norm = None
    view_7 = torch.ops.nvprims.view.default(getitem, [1, 1024, 128, 128], [16, 64, 128, 128]);  getitem = None
    le = torch.ops.nvprims.le.default(view_7, 0.0)
    where = torch.ops.nvprims.where.default(le, 0.0, view_7);  le = view_7 = None
    return (view_4, view_5, view_2, getitem_1, getitem_2, where)
```

**Comment by jjsjann123** [comment]
Somehow the broadcast in FusionDefinition is not present in the GraphModule printed... this looks strange.
But inputs the the GraphModule is named `broadcast_in_dim_xxx`. I tend to think this is because you are running it with different code base, (mostly now that we have bookend view-like ops stripped, which changes the graph).

This looks very scary to me. Wasn't this a race condition if we have running stats broadcasted and being written to?!?!

**Comment by rdspring1** [comment]
The transformed `batch_norm` likely comes from the `InstanceNorm2d` calls in pytorch_stargan.
[benchmark/model.py at main · pytorch/benchmark (github.com)](https://github.com/pytorch/benchmark/blob/main/torchbenchmark/models/pytorch_stargan/model.py#L28-L30)

**Comment by jjsjann123** [comment]
https://github.com/pytorch/pytorch/blob/c40033be162db0f94d37e7ccbd2a89d67f8b8e47/aten/src/ATen/native/Normalization.cpp#L664-L670

So this is well defined behavior. Looks like we need to fix that in decomposition.

**Comment by rdspring1** [comment]
Linking upstream issue: https://github.com/pytorch/pytorch/issues/88375
