### ISSUE TITLE
transpose kernel produces wrong result on maxwell devices

### ISSUE THREAD

**Issue by jjsjann123** [csarofeen/pytorch#2127]
### 🐛 Describe the bug

Issue shows up in upstream CI: https://github.com/pytorch/pytorch/pull/87779
I have verified the failure on devel

We are producing wrong results with transpose. Strangely this issue only repro on Maxwell, even though generated kernel looks identical on Volta with the same launch param.

```
======================================================================
FAIL [0.013s]: test_view_before_permute (__main__.TestCudaFuser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/test/test_jit_cuda_fuser.py", line 4505, in test_view_before_permute
    self._view_before_permute_helper(before_view_size, after_view_size, output_size, axes)
  File "/var/lib/jenkins/workspace/test/test_jit_cuda_fuser.py", line 4518, in _view_before_permute_helper
    self._run_helper(t_jit, t, x, y, view_shape, dims)
  File "/var/lib/jenkins/workspace/test/test_jit_cuda_fuser.py", line 213, in _run_helper
    self.assertEqual(oo, jit_oo)
  File "/var/lib/jenkins/workspace/test/test_jit_cuda_fuser.py", line 120, in assertEqual
    super(JitTestCase, self).assertEqual(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 2464, in assertEqual
    assert_equal(
  File "/opt/conda/lib/python3.10/site-packages/torch/testing/_comparison.py", line 1093, in assert_equal
    raise error_metas[0].to_error(msg)
AssertionError: Tensor-likes are not close!

Mismatched elements: 754 / 158004 (0.5%)
Greatest absolute difference: 4.238195260536907 at index (0, 13, 0, 2550, 2) (up to 1e-07 allowed)
Greatest relative difference: inf at index (0, 11, 0, 2337, 0) (up to 1e-07 allowed)
```

This is the codegen IR:
```
Inputs:
  T0_g[ bS0{1}, iS1{i2}, bS2{1}, iS3{i3}, iS4{i4} ], double
  T1_g[ bS5{1}, iS6{i5}, bS7{1}, iS8{i6}, iS9{i7} ], double
Outputs:
  T4_g[ bS20{1}, iS21{i5}, bS22{1}, iS23{i7}, iS24{i6} ], double

%kernel_math {
T2_l[ bS10{1}, iS11{i5}, bS12{1}, iS13{i7}, iS14{i6} ] = transpose( T1_g[ bS5{1}, iS6{i5}, bS7{1}, iS8{i6}, iS9{i7} ] )
T3_l[ bS15{1}, iS16{i5}, bS17{1}, iS18{i7}, iS19{i6} ]
   = T2_l[ bS10{1}, iS11{i5}, bS12{1}, iS13{i7}, iS14{i6} ]
   + T0_g[ bS0{1}, iS1{i2}, bS2{1}, iS3{i3}, iS4{i4} ];
T4_g[ bS20{1}, iS21{i5}, bS22{1}, iS23{i7}, iS24{i6} ]
   = relu(T3_l[ bS15{1}, iS16{i5}, bS17{1}, iS18{i7}, iS19{i6} ]);
}  
```

### Versions

TOT devel also has the repro on Maxwell
```
commit 7d6c8be78ba19b2827bbcd2ad06ab3a2a69d999c (HEAD, csarofeen/devel)
Author: Naoya Maruyama <naoyam@users.noreply.github.com>
Date:   Mon Oct 24 13:39:31 2022 -0700

    Reductions use outputs as read-write parameters, so mark them as read as well (#2118)

    * Reductions use outputs as read-write parameters, so mark them as read as
    well
```

**Comment by jjsjann123** [comment]
cpp test created here: https://github.com/csarofeen/pytorch/blob/issue_2127/torch/csrc/jit/codegen/cuda/test/test_gpu_transpose.cpp#L637-L663

**Comment by jjsjann123** [comment]
log our discussion internally:

There's a block sync in the code that doesn't look obvious to me in my first scan. There's a `__barrier_sync(0);` that requires independent thread scheduling (requires volta+ device).

Technically this could happen for any unroll/unswitch used in scheduling. 

Naoya suggested trying this
```
PYTORCH_NVFUSER_DISABLE=divergent_unswitch? https://github.com/csarofeen/pytorch/pull/2129
```

^^^ Let's evaluate this after upstream bump. We need to take another look at failing slow test on both volta & pre-volta devices then.

**Comment by jjsjann123** [comment]
linking upstream ci bump: https://github.com/pytorch/pytorch/pull/87779

**Comment by jjsjann123** [comment]
I'm closing this one for now since we decided to ignore pre-volta devices.
