### ISSUE TITLE
index_select type mismatch failure

### ISSUE THREAD

**Issue by naoyam** [csarofeen/pytorch#2227]
This is what I get with the TOT devel:

```
======================================================================
ERROR: test_index_select_fusion (__main__.TestCudaFuser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nmaruyama/pytorch/debug6/test/test_jit_cuda_fuser.py", line 4172, in test_index_select_fusion
    self._run_helper(t_jit, t, lookup_tv, indies_tv, sbf)
  File "/home/nmaruyama/pytorch/debug6/test/test_jit_cuda_fuser.py", line 204, in _run_helper
    jit_o = jit_op(*args)
  File "/home/nmaruyama/pytorch/debug6/torch/testing/_internal/common_utils.py", line 474, in prof_func_call
    return prof_callable(func_call, *args, **kwargs)
  File "/home/nmaruyama/pytorch/debug6/torch/testing/_internal/common_utils.py", line 471, in prof_callable
    return callable(*args, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: Incompatible operand types: int and int64_t
```

It's because the index values passed to `index_select` are type `int`, while the indexing math we generate is `int64_t`. Looks like PyTorch allows both `int64_t` and `int` as the data type of index tensors.

I think it's reasonable to do automatic type promotion in `IrBuilder` to handle these cases.

**Comment by naoyam** [comment]
Tagging #2184 as that's where the bug was originally introduced.

**Comment by naoyam** [comment]
Actually, we should just cast this to `nvfuser_index_t`. https://github.com/csarofeen/pytorch/blob/devel/torch/csrc/jit/codegen/cuda/lower_index.cpp#L200

**Comment by chang-l** [comment]
The internal `index_select` CI caught this too. Thank you @naoyam for quickly fixing this.
