### ISSUE TITLE
Test_Ternary_Ops fails in python tests

### ISSUE THREAD

**Issue by rdspring1** [csarofeen/pytorch#412]
## 🐛 Bug

```
FAIL: test_ternary_ops (test_jit_cuda_fuser.TestCudaFuser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rspring/anaconda3/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 822, in wrapper
    method(*args, **kwargs)
  File "/home/rspring/pytorch/test/test_jit_cuda_fuser.py", line 425, in test_ternary_ops
    self._run_helper(clamp0_jit, clamp0, x, 0.5)
  File "/home/rspring/pytorch/test/test_jit_cuda_fuser.py", line 66, in _run_helper
    self.assertEqual(o, jit_o)
  File "/home/rspring/anaconda3/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1131, in assertEqual
    self.assertTrue(result, msg=msg)
AssertionError: False is not true : Tensors failed to compare as equal! With rtol=1.3e-06 and atol=1e-05, found 16384 element(s) (out of 32768) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 2.547049432992935 (2.6667091846466064 vs. 0.11965975165367126), which occurred at index (3, 0, 19, 26).
```

Note: the ternary test in test_gpu.cpp runs correctly.

## To Reproduce
Run `python test/test_jit_cuda_fuser_profiling.py`

**Comment by jjsjann123** [comment]
Strangely I don't have the repro...
I tried it on both release & debug build. We are seeing a pretty big different here in the output. What's you CUDA & DRIVER version?

**Comment by rdspring1** [comment]
I was thinking it might just be my old GPU, since I'm the only one seeing the failure.

DRIVER: 450.66
CUDA: 11.0
GPU: GTX 960 4 GB

**Comment by naoyam** [comment]
I haven't seen this error. Is this still happening?

My system  has a TITAN RTX with:
```
$ nvcc --version                                                                                                      
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Wed_Jul_22_19:09:09_PDT_2020
Cuda compilation tools, release 11.0, V11.0.221
Build cuda_11.0_bu.TC445_37.28845127_0
$ cat /proc/driver/nvidia/version                                                                                             
NVRM version: NVIDIA UNIX x86_64 Kernel Module  450.51.06  Sun Jul 19 20:02:54 UTC 2020
GCC version:  gcc version 8.4.0 (Ubuntu 8.4.0-1ubuntu1~18.04)
```

**Comment by rdspring1** [comment]
I think it was a bug associated with my GTX 960. My 3090 doesn't see the issue.

**Comment by naoyam** [comment]
Could that be due to the smaller memory capacity?

**Comment by rdspring1** [comment]
Perhaps. Usually, I'd see an out-of-memory CUDA exception of the cpp tests, but the python tests might catch the exception.

**Comment by naoyam** [comment]
Can you try to run the Python test with compute-sanitizer?
