### ISSUE TITLE
NVFuser - Point-wise + Reduction Failure

### ISSUE THREAD

**Issue by rdspring1** [csarofeen/pytorch#442]
## 🐛 Bug

Failure while fusing point-wise op + reduction together. There are several failures in `test_jit_cuda_fuser.py` with the same failure message.

```
===== Reduction Parameters ========
Inputs:
	Red Elems: 4096 Red Outputs: 1024 Red On Fastest Dim? 1
Reduction Characteristics:
	Multiple Reds Per Block? 1 Cross Block? 0 Cross Grid? 0
Recommended Blocking:
	GridX: 64 GridY: -1 BlckX: 32 BlckY: 16
====================================

Traceback (most recent call last):
  File "reduction.py", line 20, in <module>
    print(my_reduction.graph_for(inputs))
  File "/home/rspring/anaconda3/lib/python3.8/site-packages/torch/jit/_fuser.py", line 69, in _graph_for
    self(*args, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: Cannot detect the origin of val,  it was not found in the active fusion.
```

## To Reproduce

```
import torch
import numpy
import os

os.environ['PYTORCH_CUDA_FUSER_DEBUG'] = '1'
os.environ['PYTORCH_CUDA_FUSER_RED_SCHED_DEBUG'] = '1'
os.environ['PYTORCH_CUDA_FUSER_DISABLE_FALLBACK'] = '1'

@torch.jit.script
def my_reduction(x: torch.Tensor):
    o = torch.sum(torch.exp(x), dim=-1)
    return o

input_shape = [1024, 4096]
with torch.jit.fuser("fuser2"):
    inputs = torch.randn(input_shape, device='cuda', dtype=torch.float)

    for idx in range(0, 5) :
        if idx == 1 :
            print(my_reduction.graph_for(inputs))
        outputs = my_reduction(inputs)       
```

**Comment by rdspring1** [comment]
It was an error in my code.
