### ISSUE TITLE
RuntimeError: guard_tensor_type && guard_tensor_type->dim().has_value()

### ISSUE THREAD

**Issue by tlemo** [csarofeen/pytorch#572]
```
kevin.py:35: UserWarning: FALLBACK path has been taken. This is an indication that codegenFailed for some reason. To debug try disable codegen fallback pathvia setting the env variable`export PYTORCH_NVFUSER_DISABLE_FALLBACK=1` (Triggered internally at  ../torch/csrc/jit/codegen/cuda/manager.cpp:255.)
  outputs = jit_model.forward(inputs)
[W manager.cpp:255] Warning: FALLBACK path has been taken. This is an indication that codegenFailed for some reason. To debug try disable codegen fallback pathvia setting the env variable`export PYTORCH_NVFUSER_DISABLE_FALLBACK=1` (function compileCudaFusionGroup)
[W manager.cpp:255] Warning: FALLBACK path has been taken. This is an indication that codegenFailed for some reason. To debug try disable codegen fallback pathvia setting the env variable`export PYTORCH_NVFUSER_DISABLE_FALLBACK=1` (function compileCudaFusionGroup)
[W manager.cpp:255] Warning: FALLBACK path has been taken. This is an indication that codegenFailed for some reason. To debug try disable codegen fallback pathvia setting the env variable`export PYTORCH_NVFUSER_DISABLE_FALLBACK=1` (function compileCudaFusionGroup)
Traceback (most recent call last):
  File "kevin.py", line 36, in <module>
    outputs.backward(grads)
  File "/home/lemo/work/pytorch/torch/tensor.py", line 233, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/lemo/work/pytorch/torch/autograd/__init__.py", line 144, in backward
    Variable._execution_engine.run_backward(
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: guard_tensor_type && guard_tensor_type->dim().has_value() INTERNAL ASSERT FAILED at "../torch/csrc/jit/codegen/cuda/interface.cpp":87, please report a bug to PyTorch. 
```

The internal call stack is:

```
libc10.so!c10::Error::Error(c10::Error * const this, std::__cxx11::string msg, std::__cxx11::string backtrace, const void * caller) (/home/lemo/work/pytorch/c10/util/Exception.cpp:15)
libc10.so!c10::Error::Error(c10::Error * const this, c10::SourceLocation source_location, std::__cxx11::string msg) (/home/lemo/work/pytorch/c10/util/Logging.cpp:70)
libtorch_cuda.so!torch::jit::fuser::cuda::(anonymous namespace)::NaiveTypePropagator::binary_broadcast_type(torch::jit::fuser::cuda::(anonymous namespace)::NaiveTypePropagator * const this, const c10::TensorTypePtr & op0, const c10::TensorTypePtr & op1, c10::optional<c10::ScalarType> scalar_type) (/home/lemo/work/pytorch/torch/csrc/jit/codegen/cuda/shape_inference.cpp:322)
libtorch_cuda.so!torch::jit::fuser::cuda::(anonymous namespace)::NaiveTypePropagator::PropagateOnNode(torch::jit::fuser::cuda::(anonymous namespace)::NaiveTypePropagator * const this, torch::jit::Node * node) (/home/lemo/work/pytorch/torch/csrc/jit/codegen/cuda/shape_inference.cpp:117)
libtorch_cuda.so!torch::jit::fuser::cuda::(anonymous namespace)::NaiveTypePropagator::PropagateOnBlock(torch::jit::fuser::cuda::(anonymous namespace)::NaiveTypePropagator * const this, torch::jit::Block * block) (/home/lemo/work/pytorch/torch/csrc/jit/codegen/cuda/shape_inference.cpp:38)
libtorch_cuda.so!torch::jit::fuser::cuda::(anonymous namespace)::NaiveTypePropagator::run(torch::jit::fuser::cuda::(anonymous namespace)::NaiveTypePropagator * const this) (/home/lemo/work/pytorch/torch/csrc/jit/codegen/cuda/shape_inference.cpp:290)
libtorch_cuda.so!torch::jit::fuser::cuda::TypePropagate(std::shared_ptr<torch::jit::Graph> & graph) (/home/lemo/work/pytorch/torch/csrc/jit/codegen/cuda/shape_inference.cpp:356)
libtorch_cuda.so!torch::jit::fuser::cuda::<lambda()>::operator()(void) const(const torch::jit::fuser::cuda::<lambda()> * const __closure) (/home/lemo/work/pytorch/torch/csrc/jit/codegen/cuda/manager.cpp:240)
libtorch_cuda.so!torch::jit::fuser::cuda::compileCudaFusionGroup(torch::jit::Node * fusion_node) (/home/lemo/work/pytorch/torch/csrc/jit/codegen/cuda/manager.cpp:249)
libtorch_cpu.so!torch::jit::fuser::cuda::compileFusionGroup(torch::jit::Node * fusion_node) (/home/lemo/work/pytorch/torch/csrc/jit/codegen/cuda/interface.cpp:27)
libtorch_cuda.so!torch::jit::fuser::cuda::(anonymous namespace)::compileFusionRecursive(torch::jit::Block * block) (/home/lemo/work/pytorch/torch/csrc/jit/codegen/cuda/graph_fuser.cpp:906)
libtorch_cuda.so!torch::jit::fuser::cuda::(anonymous namespace)::compileFusionRecursive(torch::jit::Block * block) (/home/lemo/work/pytorch/torch/csrc/jit/codegen/cuda/graph_fuser.cpp:909)
libtorch_cuda.so!torch::jit::fuser::cuda::(anonymous namespace)::compileFusionRecursive(torch::jit::Block * block) (/home/lemo/work/pytorch/torch/csrc/jit/codegen/cuda/graph_fuser.cpp:909)
libtorch_cuda.so!torch::jit::fuser::cuda::(anonymous namespace)::compileFusionRecursive(torch::jit::Block * block) (/home/lemo/work/pytorch/torch/csrc/jit/codegen/cuda/graph_fuser.cpp:909)
libtorch_cuda.so!torch::jit::fuser::cuda::CudaFuseGraph(std::shared_ptr<torch::jit::Graph> & graph) (/home/lemo/work/pytorch/torch/csrc/jit/codegen/cuda/graph_fuser.cpp:1119)
libtorch_cpu.so!torch::jit::fuser::cuda::fuseGraph(std::shared_ptr<torch::jit::Graph> & graph) (/home/lemo/work/pytorch/torch/csrc/jit/codegen/cuda/interface.cpp:41)
libtorch_python.so!std::_Function_handler<void (std::shared_ptr<torch::jit::Graph>&), void (*)(std::shared_ptr<torch::jit::Graph>&)>::_M_invoke(std::_Any_data const&, std::shared_ptr<torch::jit::Graph>&)(const std::_Any_data & __functor,  __args#0) (/usr/include/c++/8/bits/std_function.h:297)
libtorch_cpu.so!std::function<void (std::shared_ptr<torch::jit::Graph>&)>::operator()(std::shared_ptr<torch::jit::Graph>&) const(const std::function<void(std::shared_ptr<torch::jit::Graph>&)> * const this,  __args#0) (/usr/include/c++/8/bits/std_function.h:687)
libtorch_cpu.so!torch::jit::runDiffGraphPasses(std::shared_ptr<torch::jit::Graph> & graph) (/home/lemo/work/pytorch/torch/csrc/jit/runtime/profiling_graph_executor_impl.cpp:274)
libtorch_cpu.so!torch::jit::ProfilingGraphExecutorImpl::runProfilingOptimizations(torch::jit::ProfilingGraphExecutorImpl * const this, std::shared_ptr<torch::jit::Graph> & copy) (/home/lemo/work/pytorch/torch/csrc/jit/runtime/profiling_graph_executor_impl.cpp:362)
libtorch_cpu.so!torch::jit::ProfilingGraphExecutorImpl::getOptimizedPlanFor(torch::jit::ProfilingGraphExecutorImpl * const this, torch::jit::Stack & stack, size_t remaining_bailout_depth) (/home/lemo/work/pytorch/torch/csrc/jit/runtime/profiling_graph_executor_impl.cpp:502)
libtorch_cpu.so!torch::jit::ProfilingGraphExecutorImpl::getPlanFor(torch::jit::ProfilingGraphExecutorImpl * const this, torch::jit::Stack & stack, size_t remaining_bailout_depth) (/home/lemo/work/pytorch/torch/csrc/jit/runtime/profiling_graph_executor_impl.cpp:523)
libtorch_cpu.so!torch::jit::GraphExecutorImplBase::run(torch::jit::ProfilingGraphExecutorImpl * const this, torch::jit::Stack & stack) (/home/lemo/work/pytorch/torch/csrc/jit/runtime/graph_executor.cpp:520)
libtorch_cpu.so!torch::jit::GraphExecutor::run(torch::jit::GraphExecutor * const this, torch::jit::Stack & inputs) (/home/lemo/work/pytorch/torch/csrc/jit/runtime/graph_executor.cpp:740)
libtorch_cpu.so!torch::jit::GraphFunction::run(torch::jit::GraphFunction * const this, torch::jit::Stack & stack) (/home/lemo/work/pytorch/torch/csrc/jit/api/function_impl.cpp:35)
...
```

**Comment by tlemo** [comment]
Repro script:

```python
import torch.nn.functional as F
import torch.nn as nn
import torch
import time
torch._C._jit_set_nvfuser_enabled(True)
torch._C._jit_set_texpr_fuser_enabled(False)                                                                                                                                                 
torch._C._jit_set_profiling_executor(True)                                                                                                                                              
torch._C._jit_set_profiling_mode(True)                                                                                                                                                  
torch._C._jit_override_can_fuse_on_cpu(False)                                                                                                                                           
torch._C._jit_override_can_fuse_on_gpu(False)                                                                                                                                           
torch._C._jit_set_bailout_depth(20)           
class BertOutput(nn.Module):
    def __init__(self, hidden_size, hidden_dropout_prob, layer_norm_eps=1e-05):
        super().__init__()
        self.dense = nn.Linear(hidden_size, hidden_size, bias=False)
        self.LayerNorm = nn.LayerNorm(hidden_size, eps=layer_norm_eps)
        self.dropout = nn.Dropout(hidden_dropout_prob)
        self.bias = nn.Parameter(torch.zeros(hidden_size))
    def forward(self, input_tensor):
        #hidden_states = input_tensor + self.bias
        hidden_states = self.dense(input_tensor)
        hidden_states = hidden_states + self.bias
        hidden_states = self.dropout(hidden_states)
        hidden_states = hidden_states + input_tensor
        hidden_states = self.LayerNorm(hidden_states)
        return hidden_states
model = BertOutput(1024, 0.1)
model.to('cuda')
jit_model = torch.jit.script(model)
inputs = torch.randn([128, 128, 1024], device='cuda', requires_grad=True)
grads = torch.randn([128, 128, 1024], device='cuda')
for idx in range(0, 5) :
    if idx == 3 :
        print(jit_model.forward.graph_for(inputs))
    outputs = jit_model.forward(inputs)
    outputs.backward(grads)
```

**Comment by jjsjann123** [comment]
This should be a result from autodiff in JIT.

Where forward graph was expanded per autodiff substitution (node were expanded to FW/BW per `symbolic_script.cpp`), where expanded operations introduces tensors that are not profiled. Hence the lack of profiling information causes this issue.

A simple WAR is to change the FW graph execution to allow another profiling run. I opened this PR upstream to fix that (https://github.com/pytorch/pytorch/pull/47434/files). Apparently that PR is not finished yet and there are issues I haven't got around to finish, so we haven't merged it to our codebase.
For the time being, please cherry-pick that to WAR the problem. But please do NOT merge the unfinished PR yet. (sorry for the inconvenience on this, you will have a hard time getting your test to work properly)

**Comment by csarofeen** [comment]
I don't see any errors or warnings now on this repro script. Closing.
