### ISSUE TITLE
batch norm python unit test getting compute_at error on size [2, 1, 1, 1]

### ISSUE THREAD

**Issue by jjsjann123** [csarofeen/pytorch#896]
## 🐛 Bug

This used to be a codegen error but became a segfault after merging ToT. I can get a repro by modifying the python unit test.
I'm trying to merge the PR as-is, since I'm worried that codegen changes could break batch norm.

Opening this issue per review comments, I'll be taking this one right after batch norm PR merged #684

**Comment by jjsjann123** [comment]
#926 is merged. I'll update the python test to validate the fix.

**Comment by jjsjann123** [comment]
More errors found at #933

**Comment by jjsjann123** [comment]
This one surprisingly still repro (although with a different error).

I have pushed a python repro to https://github.com/csarofeen/pytorch/tree/bn_repro
```
root@f3d8903f445f:/raid/pytorch_10_1/test# python test_jit_cuda_fuser.py TestCudaFuser.test_batch_norm_impl_index_repro
E
======================================================================
ERROR: test_batch_norm_impl_index_repro (__main__.TestCudaFuser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/raid/pytorch_10_1/torch/testing/_internal/common_utils.py", line 1753, in wrapper
    method(*args, **kwargs)
  File "test_jit_cuda_fuser.py", line 3059, in test_batch_norm_impl_index_repro
    self._test_batch_norm_impl_index_helper(2, 1, 1, False, True, True)
  File "test_jit_cuda_fuser.py", line 2944, in _test_batch_norm_impl_index_helper
    jit_o.backward(grad)
  File "/raid/pytorch_10_1/torch/_tensor.py", line 352, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/raid/pytorch_10_1/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: validateDomain(producer, new_domain)INTERNAL ASSERT FAILED at "/raid/pytorch_10_1/torch/csrc/jit/codegen/cuda/compute_at.cpp":491, please report a bug to PyTorch. Tried to set the domain of T12_l[ rthreadIdx.x112{( ceilDiv(( ceilDiv(( ceilDiv(i4, 1) ), 1) ), 2) )}, sbS111{1} ] produce_pos( 1) to [ sbS111{1}, rthreadIdx.x112{( ceilDiv(( ceilDiv(( ceilDiv(i4, 1) ), 1) ), 2) )} ] but that would invalidate previously compute at position or max producer position.


----------------------------------------------------------------------
Ran 1 test in 39.508s
```

**Comment by jjsjann123** [comment]
cc'ing @csarofeen
