### ISSUE TITLE
BN forward codegen error

### ISSUE THREAD

**Issue by jjsjann123** [csarofeen/pytorch#933]
## 🐛 Bug

Running into more errors with codegen for BN on size (2, 1, 1, 1).

```
RuntimeError: it != bcast_map_.end()INTERNAL ASSERT FAILED at "../torch/csrc/jit/codegen/cuda/root_domain_map.cpp":488, please report a bug to PyTorch. Not found: {[ rS20{i9}, sbS21{1}, rS22{1}, rS23{1} ] (root: rS20{i9} sbS21{1} rS22{1} rS23{1}, maybe rfactor: rS20{i9} sbS21{1} rS22{1} rS23{1}), sbS21{1}}
```

This is the math print from the fusion

```
Inputs:
  T0[ sbS0{1} ], float
  T1[ sbS1{1} ], float
  T2[ sbS2{1} ], float
  T3[ sbS3{1} ], float
  T4[ iS4{i9}, sbS5{1}, sbS6{1}, sbS7{1} ], float
Outputs:
  T11[ sbS26{1} ], float
  T15[ sbS30{1} ], float
  T26[ iS62{i9}, sbS63{1}, sbS64{1}, sbS65{1} ], float
  T7[ rS16{i9}, sbS17{1}, rS18{1}, rS19{1} ], float
  T20[ sbS41{1} ], float
  T5[ iS8{i9}, sbS9{1}, sbS10{1}, sbS11{1} ], float

%kernel_math {
d38 = double(1) - double(0.10000000149011612);
T10[ sbS25{1} ]
   = T2[ sbS2{1} ]
   * d38;
T5[ iS8{i9}, sbS9{1}, sbS10{1}, sbS11{1} ]
   = T4[ iS4{i9}, sbS5{1}, sbS6{1}, sbS7{1} ]
   * double(1);
T6[ rS12{i9}, sbS13{1}, rS14{1}, rS15{1} ](Var), T7[ rS16{i9}, sbS17{1}, rS18{1}, rS19{1} ](Avg), T8[ rS20{i9}, sbS21{1}, rS22{1}, rS23{1} ](Count) = Welford ( T5[ iS8{i9}, sbS9{1}, sbS10{1}, sbS11{1} ] )
T9[ sbS24{1} ]
   = T7[ rS16{i9}, sbS17{1}, rS18{1}, rS19{1} ]
   * double(0.10000000149011612);
T11[ sbS26{1} ]
   = T10[ sbS25{1} ]
   + T9[ sbS24{1} ];
T14[ sbS29{1} ]
   = T3[ sbS3{1} ]
   * d38;
d30 = double(1) * i9;
d31 = d30 * 1;
d32 = d31 * 1;
d46 = d32 - 1;
T12[ sbS27{1} ]
   = T6[ rS12{i9}, sbS13{1}, rS14{1}, rS15{1} ]
   / d46;
T13[ sbS28{1} ]
   = T12[ sbS27{1} ]
   * double(0.10000000149011612);
T15[ sbS30{1} ]
   = T14[ sbS29{1} ]
   + T13[ sbS28{1} ];
T16[ bS31{1}, sbS32{1}, bS33{1}, bS34{1} ] = broadcast( T7[ rS16{i9}, sbS17{1}, rS18{1}, rS19{1} ] )
T17[ iS35{i9}, sbS36{1}, sbS37{1}, sbS38{1} ]
   = T5[ iS8{i9}, sbS9{1}, sbS10{1}, sbS11{1} ]
   - T16[ bS31{1}, sbS32{1}, bS33{1}, bS34{1} ];
T18[ sbS39{1} ]
   = T6[ rS12{i9}, sbS13{1}, rS14{1}, rS15{1} ]
   / d32;
T19[ sbS40{1} ]
   = T18[ sbS39{1} ]
   + double(9.9999997473787516e-06);
T20[ sbS41{1} ]
   = rsqrtf(T19[ sbS40{1} ]);
T21[ bS42{1}, sbS43{1}, bS44{1}, bS45{1} ] = broadcast( T20[ sbS41{1} ] )
T22[ iS46{i9}, sbS47{1}, sbS48{1}, sbS49{1} ]
   = T17[ iS35{i9}, sbS36{1}, sbS37{1}, sbS38{1} ]
   * T21[ bS42{1}, sbS43{1}, bS44{1}, bS45{1} ];
T23[ bS50{1}, sbS51{1}, bS52{1}, bS53{1} ] = broadcast( T0[ sbS0{1} ] )
T24[ iS54{i9}, sbS55{1}, sbS56{1}, sbS57{1} ] 
   = T22[ iS46{i9}, sbS47{1}, sbS48{1}, sbS49{1} ]
   * T23[ bS50{1}, sbS51{1}, bS52{1}, bS53{1} ];
T25[ bS58{1}, sbS59{1}, bS60{1}, bS61{1} ] = broadcast( T1[ sbS1{1} ] )
T26[ iS62{i9}, sbS63{1}, sbS64{1}, sbS65{1} ]
   = T24[ iS54{i9}, sbS55{1}, sbS56{1}, sbS57{1} ]
}
```

BT from gdb vvv

```
#0  0x00007fff768248c0 in c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@plt ()
   from /opt/conda/lib/python3.8/site-packages/torch/lib/libc10.so
#1  0x00007fff7688b93a in c10::detail::torchInternalAssertFail (
    func=0x7fff7d7d037b "getConcretizedKeys",
    file=0x7fff7d7cfbd8 "../torch/csrc/jit/codegen/cuda/root_domain_map.cpp", line=488,
    condMsg=0x7fff7d7d02f0 "it != bcast_map_.end()INTERNAL ASSERT FAILED at \"../torch/csrc/jit/codegen/cuda/root_domain_map.cpp\":488, please report a bug to PyTorch. ",
    userMsg="Not found: {[ rS20{i9}, sbS21{1}, rS22{1}, rS23{1} ] (root: rS20{i9} sbS21{1} rS22{1} rS23{1}, maybe rfactor: rS20{i9} sbS21{1} rS22{1} rS23{1}), sbS21{1}}")
    at ../c10/util/Exception.cpp:96
#2  0x00007fff7bfbede7 in torch::jit::fuser::cuda::ComputeAtRootDomainMap::getConcretizedKeys
    (this=0x7fffffff8600, td=0x55565a566980, id=0x55565a566b50)
    at ../torch/csrc/jit/codegen/cuda/root_domain_map.cpp:488
#3  0x00007fff7bfc191f in torch::jit::fuser::cuda::ComputeAtRootDomainMapBuilder::handle (
    this=0x7fffffff8380, tv=0x55565a53e340)
    at ../torch/csrc/jit/codegen/cuda/root_domain_map.cpp:832
#4  0x00007fff7bdc9d79 in torch::jit::fuser::cuda::Val::dispatch<torch::jit::fuser::cuda::OptOutDispatch*> (handler=0x7fffffff8380, val=0x55565a53e340)
    at ../torch/csrc/jit/codegen/cuda/dispatch.cpp:68
#5  0x00007fff7bdc817b in torch::jit::fuser::cuda::OptOutDispatch::handle (
    this=0x7fffffff8380, v=0x55565a53e340) at ../torch/csrc/jit/codegen/cuda/dispatch.cpp:346
#6  0x00007fff7bec15fb in torch::jit::fuser::cuda::BackwardVisitor::handle (
    this=0x7fffffff8380, val=0x55565a53e340)
    at ../torch/csrc/jit/codegen/cuda/iter_visitor.cpp:280
#7  0x00007fff7bdc989b in torch::jit::fuser::cuda::Statement::dispatch<torch::jit::fuser::cuda::OptOutDispatch*> (handler=0x7fffffff8380, stmt=0x55565a53e340)
    at ../torch/csrc/jit/codegen/cuda/dispatch.cpp:120
#8  0x00007fff7bdc8127 in torch::jit::fuser::cuda::OptOutDispatch::handle (
    this=0x7fffffff8380, s=0x55565a53e340) at ../torch/csrc/jit/codegen/cuda/dispatch.cpp:338
#9  0x00007fff7bec15a7 in torch::jit::fuser::cuda::BackwardVisitor::handle (
    this=0x7fffffff8380, stmt=0x55565a53e340)
    at ../torch/csrc/jit/codegen/cuda/iter_visitor.cpp:272
#10 0x00007fff7bec1bd9 in torch::jit::fuser::cuda::BackwardVisitor::traverseFrom (
    this=0x7fffffff8380, fusion=0x55565a5611a0,
    from=std::vector of length 6, capacity 8 = {...}, traverseAllPaths=false)
    at ../torch/csrc/jit/codegen/cuda/iter_visitor.cpp:347
#11 0x00007fff7bfbfe59 in torch::jit::fuser::cuda::ComputeAtRootDomainMapBuilder::ComputeAtRootDomainMapBuilder (this=0x7fffffff8380, root_map=..., map_through_reduction=true)
    at ../torch/csrc/jit/codegen/cuda/root_domain_map.cpp:623
#12 0x00007fff7bfbddf2 in torch::jit::fuser::cuda::ComputeAtRootDomainMap::build (
    this=0x7fffffff8600, map_through_reduction=true)
    at ../torch/csrc/jit/codegen/cuda/root_domain_map.cpp:344
#13 0x00007fff7bfef303 in torch::jit::fuser::cuda::(anonymous namespace)::NormalizationScheduler::canSchedule (fusion=0x55565a5611a0, runtime_info=...)
    at ../torch/csrc/jit/codegen/cuda/scheduler/registry.cpp:662
--Type <RET> for more, q to quit, c to continue without paging--
#14 0x00007fff7bfefaae in torch::jit::fuser::cuda::SchedulerEntry::canSchedule (
    sh=torch::jit::fuser::cuda::ScheduleHeuristic::Normalization, fusion=0x55565a5611a0,
    runtime_info=...) at ../torch/csrc/jit/codegen/cuda/scheduler/registry.cpp:746
#15 0x00007fff7bfefcab in torch::jit::fuser::cuda::SchedulerEntry::proposeHeuristics
```

## To Reproduce

I got a cpp repro to `https://github.com/csarofeen/pytorch/tree/bn_repro_3`, build and run with `./build/bin/test_jit --gtest_filter="*BNRepro_CUDA*"`

**Comment by jjsjann123** [comment]
Verified that this doesn't repro any more.
